import 'package:flutter/widgets.dart';
import 'package:tt_mail_assistant/core/di/di.dart';
import 'package:tt_mail_assistant/core/localization/app_language_controller.dart';

class AppLocalizations {
  const AppLocalizations(this.language);

  final AppLanguage language;

  bool get isFrench => language == AppLanguage.french;

  String t(String key) {
    if (!isFrench) return _english[key] ?? key;
    return _french[key] ?? _english[key] ?? key;
  }

  String languageName(AppLanguage value) {
    return value == AppLanguage.french ? 'Français' : 'English';
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n {
    return AppLocalizations(getIt<AppLanguageController>().language);
  }
}

const Map<String, String> _english = {
  'language.title': 'Choose your language',
  'language.subtitle':
      'You can change this later from Settings. The assistant will use the same language for drafts by default.',
  'language.english': 'English',
  'language.french': 'Français',
  'language.continue': 'Continue',
  'nav.home': 'Home',
  'nav.today': 'Today',
  'nav.review': 'Review',
  'nav.profile': 'Profile',
  'auth.signInTitle': 'Sign in to your intelligent inbox',
  'auth.signInSubtitle':
      'Connect Outlook to classify messages, prepare safe drafts, and keep every action under your control.',
  'auth.connecting': 'Connecting...',
  'auth.continueOutlook': 'Continue with Outlook',
  'auth.errorOutlook': 'Unable to sign in with Outlook. Please try again.',
  'onboarding.skip': 'Skip',
  'onboarding.openAssistant': 'Open assistant',
  'onboarding.getStarted': 'Get started',
  'onboarding.connected': 'Outlook connected',
  'onboarding.primary': '12 primary',
  'onboarding.priority': '5 priority',
  'onboarding.connectTitle': 'Connect your inbox',
  'onboarding.connectDescription':
      'Let TT Mail Assistant classify, prioritize, and draft replies before email noise reaches you.',
  'onboarding.reviewProtected': 'Review protected',
  'onboarding.urgentHeld': 'Urgent held',
  'onboarding.draftChecked': 'Draft checked',
  'onboarding.controlTitle': 'Keep control',
  'onboarding.controlDescription':
      'Urgent or uncertain replies wait for your review, while safe routine emails move quietly.',
  'onboarding.repliesReady': 'Replies ready',
  'onboarding.drafts': '3 drafts',
  'onboarding.approve': '1 tap approve',
  'onboarding.answerTitle': 'Answer faster',
  'onboarding.answerDescription':
      'Approve, edit, or ignore AI drafts from one calm mobile workspace built for daily triage.',
  'settings.title': 'Settings',
  'settings.subtitle': 'Manage your account and email preferences.',
  'settings.emailHandling': 'Email handling',
  'settings.preferences': 'Preferences',
  'settings.appLanguage': 'App language',
  'settings.replyLanguage': 'Reply language',
  'settings.replyLanguageSubtitle': 'Draft replies in this language.',
  'settings.prepareReplies': 'Prepare replies automatically',
  'settings.prepareRepliesOn':
      'New unread emails are turned into drafts for review.',
  'settings.prepareRepliesOff':
      'New emails will wait until this is turned back on.',
  'settings.notifications': 'Notifications',
  'settings.notificationsSubtitle':
      'Get alerts when a reply is ready to review.',
  'settings.dailySummary': 'Daily summary',
  'settings.dailySummarySubtitle': 'Receive a short recap of handled emails.',
  'settings.darkMode': 'Dark mode',
  'settings.darkModeSubtitle': 'Use the app with a darker appearance.',
  'settings.outlookConnected': 'Outlook connected',
  'settings.signOut': 'Sign out',
  'settings.signOutTitle': 'Sign out?',
  'settings.signOutMessage':
      'You will need to connect your Outlook account again.',
  'settings.cancel': 'Cancel',
  'settings.signOutAction': 'Sign out',
  'settings.user': 'User',
  'common.back': 'Back',
  'home.error': 'Error',
  'home.recentActivity': 'Recent activity',
  'home.noRecentActivity': 'No recent activity',
  'home.processedAppear': 'Processed emails will appear here.',
  'home.shortcuts': 'Shortcuts',
  'home.tools': 'Tools',
  'home.goodMorning': 'Good morning',
  'home.goodAfternoon': 'Good afternoon',
  'home.goodEvening': 'Good evening',
  'home.notifications': 'Notifications',
  'home.repliesNeedReview': 'replies need review',
  'home.inboxUnderControl': 'Inbox is under control',
  'home.openReview': 'Open Review to check drafts before sending.',
  'home.newUnreadAppear':
      'New unread emails will appear here after the agents process them.',
  'home.processedToday': 'Processed today',
  'home.sent': 'Sent',
  'home.needReview': 'Need review',
  'home.completion': 'Completion',
  'home.noSubject': '(No subject)',
  'home.unknownSender': 'Unknown sender',
  'home.reviewReplies': 'Review replies',
  'home.groupDrafts': 'Group drafts',
  'home.formations': 'Formations',
  'formations.title': 'Formations',
  'formations.subtitle': 'Planning, participants, and Outlook drafts.',
  'formations.uploadTitle': 'Add monthly planning',
  'formations.uploadSubtitle':
      'Import up to 5 Excel files before preparing confirmation and awareness emails.',
  'formations.uploadAction': 'Add planning files',
  'formations.uploadNext':
      'Planning upload will be connected in the next step.',
  'formations.refresh': 'Refresh',
  'formations.pickError': 'Unable to read the selected Excel files.',
  'formations.uploadLimit': 'Only the first 5 planning files were selected.',
  'formations.importDone': 'Planning imported successfully.',
  'formations.draftsDone': 'Drafts are ready for review.',
  'formations.automationDone':
      'Automation completed. Drafts are ready for review.',
  'formations.monthPlan': 'Month overview',
  'formations.sessions': 'Sessions',
  'formations.participants': 'Participants',
  'formations.drafts': 'Drafts',
  'formations.missing': 'Missing data',
  'formations.reviewBeforeSend': 'Review before send',
  'formations.reviewBeforeSendHint':
      'Generated training emails stay blocked until you review, edit, and approve them.',
  'formations.generateDrafts': 'Generate training drafts',
  'formations.runAutomation': 'Run automation',
  'formations.importReady': 'ready',
  'formations.waitingImport': 'waiting',
  'formations.waitingReview': 'Review',
  'formations.approved': 'Approved',
  'formations.blocked': 'Blocked',
  'formations.draftsToReview': 'Drafts to review',
  'formations.noDrafts':
      'No drafts yet. Import a planning file, then generate training emails.',
  'formations.contactsToComplete': 'Contacts to complete',
  'formations.noSubject': '(No subject)',
  'formations.noRecipients': 'No recipient yet',
  'formations.reviewDraft': 'Review draft',
  'formations.recipients': 'Recipients',
  'formations.cc': 'Cc',
  'formations.optional': 'Optional',
  'formations.subject': 'Subject',
  'formations.message': 'Message',
  'formations.reject': 'Reject',
  'formations.save': 'Save',
  'formations.approve': 'Approve',
  'formations.sendWithOutlook': 'Send with Outlook',
  'formations.statusApproved': 'approved',
  'formations.statusEdited': 'edited',
  'formations.statusNeedsContacts': 'contacts',
  'formations.statusRejected': 'rejected',
  'formations.statusSent': 'sent',
  'formations.statusWaiting': 'review',
  'formations.workflow': 'Workflow',
  'formations.stepImport': 'Import Excel planning',
  'formations.stepValidate': 'Validate participants and emails',
  'formations.stepDraft': 'Prepare French Outlook drafts',
  'formations.stepSend': 'Review, edit, and send',
  'formations.emptyTitle': 'No planning imported',
  'formations.emptySubtitle':
      'Sessions, participants, drafts, and send history will appear after the first import.',
  'date.monday': 'Monday',
  'date.tuesday': 'Tuesday',
  'date.wednesday': 'Wednesday',
  'date.thursday': 'Thursday',
  'date.friday': 'Friday',
  'date.saturday': 'Saturday',
  'date.sunday': 'Sunday',
  'date.jan': 'Jan',
  'date.feb': 'Feb',
  'date.mar': 'Mar',
  'date.apr': 'Apr',
  'date.may': 'May',
  'date.jun': 'Jun',
  'date.jul': 'Jul',
  'date.aug': 'Aug',
  'date.sep': 'Sep',
  'date.oct': 'Oct',
  'date.nov': 'Nov',
  'date.dec': 'Dec',
  'review.title': 'Review replies',
  'review.subtitle': 'Check suggested replies before they are sent.',
  'review.urgent': 'urgent',
  'review.ready': 'ready',
  'review.readyToSend': 'ready to send',
  'filter.all': 'All',
  'filter.ready': 'Ready',
  'filter.urgent': 'Urgent',
  'filter.needsEdit': 'Needs edit',
  'assistant.title': 'Ask the assistant',
  'assistant.working': 'Working on your request',
  'assistant.ready': 'Ready for email tasks',
  'assistant.unreachable':
      'I could not reach the assistant. Check the backend services and try again.',
  'assistant.confirmed': 'Action confirmed successfully.',
  'assistant.cancelled': 'Action cancelled.',
  'assistant.unreadSummary': 'Unread summary',
  'assistant.urgentEmails': 'Urgent emails',
  'assistant.classifyInbox': 'Classify inbox',
  'assistant.reviewQueue': 'Review queue',
  'assistant.promptUnread': 'Read and summarize my latest unread email',
  'assistant.promptUrgent': 'Show me my urgent emails',
  'assistant.promptClassify': 'Classify my inbox',
  'assistant.promptReview': 'What emails are ready for review?',
  'assistant.thinking': 'Thinking',
  'assistant.inputHint': 'Ask about your emails...',
  'assistant.emptyTitle': 'What should we handle?',
  'assistant.emptySubtitle':
      'Ask for summaries, priorities, draft replies, or review queue updates.',
  'assistant.summarizeLatest': 'Summarize latest',
  'assistant.findUrgent': 'Find urgent',
  'assistant.confirmAction': 'Confirm action',
  'assistant.confirm': 'Confirm',
  'today.title': 'Today',
  'today.subtitle': 'Follow what happened with your emails today.',
  'today.previousDay': 'Previous day',
  'today.waitingReview': 'waiting for review',
  'today.yesterday': 'Yesterday',
  'today.refreshHint': 'Pull down to refresh the activity timeline.',
  'today.emptyAll': 'No activity for this day',
  'today.emptySent': 'No sent replies',
  'today.emptyReview': 'Nothing waiting for review',
  'today.emptyLow': 'No low-priority emails',
  'filter.sent': 'Sent',
  'filter.review': 'Review',
  'filter.low': 'Low',
  'bulk.campaign': 'Campaign',
  'bulk.recipients': 'Recipients',
  'bulk.added': 'added',
  'bulk.preparing': 'Preparing your drafts',
  'bulk.generate': 'Generate drafts',
  'bulk.previewEdit': 'Preview and edit',
  'notifications.title': 'Notifications',
  'notifications.subtitle': 'Your review queue and recent email activity.',
  'notifications.updated': 'Updated',
  'notifications.needsEdit': 'needs edit',
  'notifications.emptyTitle': 'Nothing needs attention',
  'notifications.emptySubtitle':
      'Replies ready for review, urgent emails, and recent sent activity will appear here.',
};

const Map<String, String> _french = {
  'language.title': 'Choisissez votre langue',
  'language.subtitle':
      'Vous pourrez la modifier plus tard dans les paramètres. L’assistant utilisera aussi cette langue pour les brouillons par défaut.',
  'language.english': 'English',
  'language.french': 'Français',
  'language.continue': 'Continuer',
  'nav.home': 'Accueil',
  'nav.today': 'Aujourd’hui',
  'nav.review': 'Revue',
  'nav.profile': 'Profil',
  'auth.signInTitle': 'Connectez-vous à votre boîte intelligente',
  'auth.signInSubtitle':
      'Connectez Outlook pour classer les messages, préparer des brouillons sûrs et garder chaque action sous votre contrôle.',
  'auth.connecting': 'Connexion...',
  'auth.continueOutlook': 'Continuer avec Outlook',
  'auth.errorOutlook':
      'Impossible de se connecter avec Outlook. Veuillez réessayer.',
  'onboarding.skip': 'Passer',
  'onboarding.openAssistant': 'Ouvrir l’assistant',
  'onboarding.getStarted': 'Commencer',
  'onboarding.connected': 'Outlook connecté',
  'onboarding.primary': '12 principaux',
  'onboarding.priority': '5 prioritaires',
  'onboarding.connectTitle': 'Connectez votre boîte mail',
  'onboarding.connectDescription':
      'Laissez TT Mail Assistant classer, prioriser et préparer des réponses avant que les emails ne vous submergent.',
  'onboarding.reviewProtected': 'Revue protégée',
  'onboarding.urgentHeld': 'Urgents retenus',
  'onboarding.draftChecked': 'Brouillon vérifié',
  'onboarding.controlTitle': 'Gardez le contrôle',
  'onboarding.controlDescription':
      'Les réponses urgentes ou incertaines attendent votre validation, tandis que les emails simples avancent discrètement.',
  'onboarding.repliesReady': 'Réponses prêtes',
  'onboarding.drafts': '3 brouillons',
  'onboarding.approve': 'Valider en 1 geste',
  'onboarding.answerTitle': 'Répondez plus vite',
  'onboarding.answerDescription':
      'Validez, modifiez ou ignorez les brouillons IA depuis un espace mobile clair pour le tri quotidien.',
  'settings.title': 'Paramètres',
  'settings.subtitle': 'Gérez votre compte et vos préférences email.',
  'settings.emailHandling': 'Traitement des emails',
  'settings.preferences': 'Préférences',
  'settings.appLanguage': 'Langue de l’application',
  'settings.replyLanguage': 'Langue des réponses',
  'settings.replyLanguageSubtitle': 'Rédiger les brouillons dans cette langue.',
  'settings.prepareReplies': 'Préparer les réponses automatiquement',
  'settings.prepareRepliesOn':
      'Les nouveaux emails non lus deviennent des brouillons à vérifier.',
  'settings.prepareRepliesOff':
      'Les nouveaux emails attendront que cette option soit réactivée.',
  'settings.notifications': 'Notifications',
  'settings.notificationsSubtitle':
      'Recevoir une alerte quand une réponse est prête à vérifier.',
  'settings.dailySummary': 'Résumé quotidien',
  'settings.dailySummarySubtitle':
      'Recevoir un court résumé des emails traités.',
  'settings.darkMode': 'Mode sombre',
  'settings.darkModeSubtitle': 'Utiliser une apparence plus sombre.',
  'settings.outlookConnected': 'Outlook connecté',
  'settings.signOut': 'Déconnexion',
  'settings.signOutTitle': 'Se déconnecter ?',
  'settings.signOutMessage': 'Vous devrez reconnecter votre compte Outlook.',
  'settings.cancel': 'Annuler',
  'settings.signOutAction': 'Se déconnecter',
  'settings.user': 'Utilisateur',
  'common.back': 'Retour',
  'home.error': 'Erreur',
  'home.recentActivity': 'Activité récente',
  'home.noRecentActivity': 'Aucune activité récente',
  'home.processedAppear': 'Les emails traités apparaîtront ici.',
  'home.shortcuts': 'Raccourcis',
  'home.tools': 'Outils',
  'home.goodMorning': 'Bonjour',
  'home.goodAfternoon': 'Bon après-midi',
  'home.goodEvening': 'Bonsoir',
  'home.notifications': 'Notifications',
  'home.repliesNeedReview': 'réponses à vérifier',
  'home.inboxUnderControl': 'Boîte mail sous contrôle',
  'home.openReview':
      'Ouvrez la revue pour vérifier les brouillons avant envoi.',
  'home.newUnreadAppear':
      'Les nouveaux emails non lus apparaîtront ici après traitement.',
  'home.processedToday': 'Traités aujourd’hui',
  'home.sent': 'Envoyés',
  'home.needReview': 'À vérifier',
  'home.completion': 'Finalisation',
  'home.noSubject': '(Sans objet)',
  'home.unknownSender': 'Expéditeur inconnu',
  'home.reviewReplies': 'Revoir les réponses',
  'home.groupDrafts': 'Brouillons groupés',
  'home.formations': 'Formations',
  'formations.title': 'Formations',
  'formations.subtitle': 'Planning, participants et brouillons Outlook.',
  'formations.uploadTitle': 'Ajouter le planning du mois',
  'formations.uploadSubtitle':
      'Importez jusqu’à 5 fichiers Excel avant de préparer les emails de confirmation et de sensibilisation.',
  'formations.uploadAction': 'Ajouter des plannings',
  'formations.uploadNext':
      'L’import du planning sera connecté à l’étape suivante.',
  'formations.refresh': 'Actualiser',
  'formations.pickError': 'Impossible de lire les fichiers Excel selectionnes.',
  'formations.uploadLimit': 'Seuls les 5 premiers fichiers ont ete retenus.',
  'formations.importDone': 'Planning importe avec succes.',
  'formations.draftsDone': 'Brouillons prets pour verification.',
  'formations.automationDone':
      'Automatisation terminee. Brouillons prets pour verification.',
  'formations.monthPlan': 'Vue du mois',
  'formations.sessions': 'Sessions',
  'formations.participants': 'Participants',
  'formations.drafts': 'Brouillons',
  'formations.missing': 'Données manquantes',
  'formations.reviewBeforeSend': 'Verifier avant envoi',
  'formations.reviewBeforeSendHint':
      'Les emails de formation restent bloques jusqu a verification, modification et validation.',
  'formations.generateDrafts': 'Generer les brouillons',
  'formations.runAutomation': 'Lancer l automatisation',
  'formations.importReady': 'pret',
  'formations.waitingImport': 'en attente',
  'formations.waitingReview': 'Revue',
  'formations.approved': 'Valides',
  'formations.blocked': 'Bloques',
  'formations.draftsToReview': 'Brouillons a verifier',
  'formations.noDrafts':
      'Aucun brouillon. Importez un planning puis generez les emails de formation.',
  'formations.contactsToComplete': 'Contacts a completer',
  'formations.noSubject': '(Sans objet)',
  'formations.noRecipients': 'Aucun destinataire',
  'formations.reviewDraft': 'Verifier le brouillon',
  'formations.recipients': 'Destinataires',
  'formations.cc': 'Cc',
  'formations.optional': 'Optionnel',
  'formations.subject': 'Objet',
  'formations.message': 'Message',
  'formations.reject': 'Refuser',
  'formations.save': 'Enregistrer',
  'formations.approve': 'Valider',
  'formations.sendWithOutlook': 'Envoyer avec Outlook',
  'formations.statusApproved': 'valide',
  'formations.statusEdited': 'modifie',
  'formations.statusNeedsContacts': 'contacts',
  'formations.statusRejected': 'refuse',
  'formations.statusSent': 'envoye',
  'formations.statusWaiting': 'revue',
  'formations.workflow': 'Traitement',
  'formations.stepImport': 'Importer le planning Excel',
  'formations.stepValidate': 'Vérifier les participants et emails',
  'formations.stepDraft': 'Préparer les brouillons Outlook en français',
  'formations.stepSend': 'Revoir, modifier et envoyer',
  'formations.emptyTitle': 'Aucun planning importé',
  'formations.emptySubtitle':
      'Les sessions, participants, brouillons et historiques d’envoi apparaîtront après le premier import.',
  'date.monday': 'Lundi',
  'date.tuesday': 'Mardi',
  'date.wednesday': 'Mercredi',
  'date.thursday': 'Jeudi',
  'date.friday': 'Vendredi',
  'date.saturday': 'Samedi',
  'date.sunday': 'Dimanche',
  'date.jan': 'Jan',
  'date.feb': 'Fév',
  'date.mar': 'Mar',
  'date.apr': 'Avr',
  'date.may': 'Mai',
  'date.jun': 'Juin',
  'date.jul': 'Juil',
  'date.aug': 'Août',
  'date.sep': 'Sep',
  'date.oct': 'Oct',
  'date.nov': 'Nov',
  'date.dec': 'Déc',
  'review.title': 'Revoir les réponses',
  'review.subtitle': 'Vérifiez les réponses suggérées avant leur envoi.',
  'review.urgent': 'urgent',
  'review.ready': 'prêtes',
  'review.readyToSend': 'prêtes à envoyer',
  'filter.all': 'Tous',
  'filter.ready': 'Prêtes',
  'filter.urgent': 'Urgentes',
  'filter.needsEdit': 'À modifier',
  'assistant.title': 'Demander à l’assistant',
  'assistant.working': 'Traitement de votre demande',
  'assistant.ready': 'Prêt pour les tâches email',
  'assistant.unreachable':
      'Impossible de joindre l’assistant. Vérifiez les services backend puis réessayez.',
  'assistant.confirmed': 'Action confirmée avec succès.',
  'assistant.cancelled': 'Action annulée.',
  'assistant.unreadSummary': 'Résumé non lu',
  'assistant.urgentEmails': 'Emails urgents',
  'assistant.classifyInbox': 'Classer la boîte',
  'assistant.reviewQueue': 'File de revue',
  'assistant.promptUnread': 'Lis et résume mon dernier email non lu',
  'assistant.promptUrgent': 'Montre-moi mes emails urgents',
  'assistant.promptClassify': 'Classe ma boîte mail',
  'assistant.promptReview': 'Quels emails sont prêts à être vérifiés ?',
  'assistant.thinking': 'Réflexion',
  'assistant.inputHint': 'Posez une question sur vos emails...',
  'assistant.emptyTitle': 'Que voulez-vous traiter ?',
  'assistant.emptySubtitle':
      'Demandez des résumés, priorités, brouillons ou mises à jour de la revue.',
  'assistant.summarizeLatest': 'Résumer le dernier',
  'assistant.findUrgent': 'Trouver les urgents',
  'assistant.confirmAction': 'Confirmer l’action',
  'assistant.confirm': 'Confirmer',
  'today.title': 'Aujourd’hui',
  'today.subtitle': 'Suivez ce qui s’est passé avec vos emails aujourd’hui.',
  'today.previousDay': 'Jour précédent',
  'today.waitingReview': 'en attente de revue',
  'today.yesterday': 'Hier',
  'today.refreshHint': 'Tirez vers le bas pour actualiser la chronologie.',
  'today.emptyAll': 'Aucune activité pour ce jour',
  'today.emptySent': 'Aucune réponse envoyée',
  'today.emptyReview': 'Rien en attente de revue',
  'today.emptyLow': 'Aucun email de faible priorité',
  'filter.sent': 'Envoyés',
  'filter.review': 'Revue',
  'filter.low': 'Faible',
  'bulk.campaign': 'Campagne',
  'bulk.recipients': 'Destinataires',
  'bulk.added': 'ajoutés',
  'bulk.preparing': 'Préparation de vos brouillons',
  'bulk.generate': 'Générer les brouillons',
  'bulk.previewEdit': 'Prévisualiser et modifier',
  'notifications.title': 'Notifications',
  'notifications.subtitle': 'Votre file de revue et l’activité récente.',
  'notifications.updated': 'Mis à jour',
  'notifications.needsEdit': 'à modifier',
  'notifications.emptyTitle': 'Rien ne demande votre attention',
  'notifications.emptySubtitle':
      'Les réponses prêtes, emails urgents et envois récents apparaîtront ici.',
};
