import 'package:flutter/widgets.dart';
import 'package:tt_mail_assistant/core/di/di.dart';
import 'package:tt_mail_assistant/core/localization/app_language_controller.dart';

class AppLocalizations {
  const AppLocalizations(this.language);

  final AppLanguage language;

  bool get isFrench => language == AppLanguage.french;

  String t(String key) {
    if (!isFrench) return _english[key] ?? key;
    return _french[key] ?? _english[key] ?? key;
  }

  String languageName(AppLanguage value) {
    return value == AppLanguage.french ? 'Français' : 'English';
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n {
    return AppLocalizations(getIt<AppLanguageController>().language);
  }
}

const Map<String, String> _english = {
  'language.title': 'Choose your language',
  'language.subtitle':
      'You can change this later in Settings. Drafts will use the same language by default.',
  'language.english': 'English',
  'language.french': 'Français',
  'language.continue': 'Continue',
  'nav.home': 'Home',
  'nav.today': 'Today',
  'nav.review': 'Review',
  'nav.profile': 'Profile',
  'common.loading': 'Loading...',
  'common.notAvailable': 'Not available',
  'auth.signInTitle': 'Sign in to your smart inbox',
  'auth.signInSubtitle':
      'Connect Outlook to classify messages, prepare safe drafts, and keep every action under your control.',
  'auth.connecting': 'Connecting...',
  'auth.continueOutlook': 'Continue with Outlook',
  'auth.errorOutlook': 'Unable to sign in with Outlook. Please try again.',
  'onboarding.skip': 'Skip',
  'onboarding.openAssistant': 'Open assistant',
  'onboarding.getStarted': 'Get started',
  'onboarding.connected': 'Outlook connected',
  'onboarding.primary': '12 primary',
  'onboarding.priority': '5 priority',
  'onboarding.connectTitle': 'Connect your inbox',
  'onboarding.connectDescription':
      'Let TT Mail Assistant classify, prioritize, and draft replies before email noise reaches you.',
  'onboarding.reviewProtected': 'Review protected',
  'onboarding.urgentHeld': 'Urgent held',
  'onboarding.draftChecked': 'Draft checked',
  'onboarding.controlTitle': 'Keep control',
  'onboarding.controlDescription':
      'Urgent or uncertain replies wait for your review, while safe routine emails move quietly.',
  'onboarding.repliesReady': 'Replies ready',
  'onboarding.drafts': '3 drafts',
  'onboarding.approve': '1 tap approve',
  'onboarding.answerTitle': 'Answer faster',
  'onboarding.answerDescription':
      'Approve, edit, or ignore AI drafts from one calm mobile workspace built for daily triage.',
  'settings.title': 'Settings',
  'settings.subtitle': 'Manage your account and email preferences.',
  'settings.emailHandling': 'Email handling',
  'settings.preferences': 'Preferences',
  'settings.appLanguage': 'App language',
  'settings.replyLanguage': 'Reply language',
  'settings.replyLanguageSubtitle': 'Draft replies in this language.',
  'settings.prepareReplies': 'Prepare replies automatically',
  'settings.prepareRepliesOn':
      'New unread emails are turned into drafts for review.',
  'settings.prepareRepliesOff':
      'New emails will wait until this is turned back on.',
  'settings.notifications': 'Notifications',
  'settings.notificationsSubtitle':
      'Get alerts when a reply is ready to review.',
  'settings.dailySummary': 'Daily summary',
  'settings.dailySummarySubtitle': 'Receive a short recap of handled emails.',
  'settings.darkMode': 'Dark mode',
  'settings.darkModeSubtitle': 'Use the app with a darker appearance.',
  'settings.outlookConnected': 'Outlook connected',
  'settings.signOut': 'Sign out',
  'settings.signOutTitle': 'Sign out?',
  'settings.signOutMessage':
      'You will need to connect your Outlook account again.',
  'settings.cancel': 'Cancel',
  'settings.signOutAction': 'Sign out',
  'settings.user': 'User',
  'common.back': 'Back',
  'common.close': 'Close',
  'home.error': 'Error',
  'home.recentActivity': 'Recent activity',
  'home.noRecentActivity': 'No recent activity',
  'home.processedAppear': 'Processed emails will appear here.',
  'home.shortcuts': 'Shortcuts',
  'home.tools': 'Tools',
  'home.goodMorning': 'Good morning',
  'home.goodAfternoon': 'Good afternoon',
  'home.goodEvening': 'Good evening',
  'home.notifications': 'Notifications',
  'home.repliesNeedReview': 'replies need review',
  'home.inboxUnderControl': 'Inbox is under control',
  'home.openReview': 'Open Review to check drafts before sending.',
  'home.newUnreadAppear':
      'New unread emails will appear here after the agents process them.',
  'home.processedToday': 'Processed emails',
  'home.sent': 'Sent',
  'home.needReview': 'Need review',
  'home.completion': 'Completion',
  'home.noSubject': '(No subject)',
  'home.unknownSender': 'Unknown sender',
  'home.reviewReplies': 'Review replies',
  'home.reviewRepliesShortcut': 'Check suggested replies before sending.',
  'home.groupDrafts': 'Group drafts',
  'home.groupDraftsShortcut': 'Prepare the same message for many recipients.',
  'home.formations': 'Formations',
  'home.formationsShortcut': 'Import planning and prepare training emails.',
  'formations.title': 'Formations',
  'formations.subtitle': 'Planning, participants, and Outlook drafts.',
  'formations.activePlan': 'Current planning is ready',
  'formations.activePlanHint': 'Continue from the step that needs attention.',
  'formations.noActivePlan': 'Start with a planning file',
  'formations.noActivePlanHint': 'Import the monthly Excel planning to begin.',
  'formations.workflowTitle': 'Training workflow',
  'formations.imports': 'imports',
  'formations.total': 'total',
  'formations.toCheck': 'to check',
  'formations.importStepTitle': 'Session planning',
  'formations.importStepSubtitle': 'Import the training session Excel file.',
  'formations.contactsStepTitle': 'Responsible contacts',
  'formations.contactsStepSubtitle': 'Search the RH/DR/DC directory.',
  'formations.calendarStepTitle': 'Calendar',
  'formations.calendarStepSubtitle': 'Review sessions by training date.',
  'formations.draftsStepTitle': 'Drafts',
  'formations.draftsStepSubtitle': 'Generate, review, and mark as sent.',
  'formations.historyStepTitle': 'Sent emails',
  'formations.historyStepSubtitle': 'Read recent Outlook Sent Items.',
  'formations.importPageTitle': 'Import formations',
  'formations.importPageSubtitle':
      'Add the session planning file, then the participant list.',
  'formations.calendarPageTitle': 'Training calendar',
  'formations.calendarPageSubtitle': 'Browse sessions by day.',
  'formations.draftsPageTitle': 'Draft review',
  'formations.draftsPageSubtitle':
      'Check responsible confirmation emails before sending.',
  'formations.contactsPageTitle': 'Responsible contacts',
  'formations.contactsPageSubtitle':
      'Search and review the responsible directory.',
  'formations.historyPageTitle': 'Sent emails',
  'formations.historyPageSubtitle':
      'Review recent messages from Outlook Sent Items.',
  'formations.uploadTitle': 'Session planning file',
  'formations.uploadSubtitle':
      'Upload Excel files to detect sessions, participants, residences, and responsible staff.',
  'formations.uploadAction': 'Add session planning',
  'formations.uploadNext':
      'Planning upload will be connected in the next step.',
  'formations.refresh': 'Refresh',
  'formations.pickError': 'Unable to read the selected session planning files.',
  'formations.uploadLimit': 'Only the first 5 files were selected.',
  'formations.importDone': 'Planning imported successfully.',
  'formations.importFeedbackTitle': 'Planning import result',
  'formations.importPreviewTitle': 'Preview planning import',
  'formations.importFeedbackClean':
      'Planning is ready. No blocking issue was found.',
  'formations.importPreviewClean':
      'This planning looks ready to import. Nothing has been saved yet.',
  'formations.importFeedbackNeedsReview':
      'Planning was imported, but a few items need attention.',
  'formations.importPreviewNeedsReview':
      'Review these points before saving the planning.',
  'formations.importNoEmailsDetectedSummary':
      'Candidate rows were found. Responsible emails are still missing.',
  'formations.importPreviewNotSaved':
      'This is only a preview. Confirm to save the planning and prepare drafts if automation is enabled.',
  'formations.confirmImport': 'Import planning',
  'formations.feedbackFiles': 'Files',
  'formations.feedbackMissingEmails': 'Missing responsible staff',
  'formations.feedbackEmailsDetected': 'Responsible staff detected',
  'formations.feedbackNoEmailsDetected':
      'Candidate emails are not required. Drafts are prepared for RH/DR/DC responsible staff by residence.',
  'formations.feedbackAutomationRan':
      'Automation prepared {generated} drafts and skipped {skipped} existing ones.',
  'formations.feedbackAutomationSkipped':
      'Automatic draft preparation is off. You can run it when ready.',
  'formations.feedbackIssueCount':
      '{warnings} warnings and {errors} errors were found.',
  'formations.feedbackFilesTitle': 'Imported files',
  'formations.feedbackFileSessions': '{count} sessions found',
  'formations.importStatusOk': 'ready',
  'formations.importStatusReview': 'review',
  'formations.importStatusError': 'error',
  'formations.importStatusUnknown': 'unknown',
  'formations.draftsDone': 'Drafts are ready for review.',
  'formations.automationDone':
      'Automation completed. Drafts are ready for review.',
  'formations.contactsTitle': 'Responsible directory',
  'formations.contactsSubtitle':
      'Responsible contacts are loaded from the database.',
  'formations.candidatesTitle': 'Candidate list',
  'formations.candidatesSubtitle':
      'Upload the Excel or CSV file with candidates by session.',
  'formations.contactsUpload': 'Upload contacts',
  'formations.contactsImported': 'Responsible contacts imported and applied.',
  'formations.responsableSearch': 'Search',
  'formations.responsableSearchHint': 'Search by name, function, or residence',
  'formations.noResponsables': 'No responsible contact found.',
  'formations.contactPickError': 'Unable to read the selected contact files.',
  'formations.fixContact': 'Fix recipient',
  'formations.emailAddress': 'Responsible email',
  'formations.invalidEmail': 'Enter a valid email address.',
  'formations.saveContact': 'Save contact',
  'formations.monthPlan': 'Month overview',
  'formations.sessions': 'Sessions',
  'formations.participants': 'Participants',
  'formations.responsibles': 'Responsible staff',
  'formations.toReview': 'To review',
  'formations.drafts': 'Drafts',
  'formations.missing': 'Missing data',
  'formations.missingResponsibleEmails': 'Missing responsible staff',
  'formations.calendarTitle': 'Training calendar',
  'formations.calendarSubtitle':
      '{count} sessions found for the selected month.',
  'formations.calendarYear': 'Year',
  'formations.calendarMonth': 'Month',
  'formations.pickMonth': 'Choose month',
  'formations.previousMonth': 'Previous month',
  'formations.nextMonth': 'Next month',
  'formations.calendarSelectionSummary':
      '{month}: {monthCount} sessions. {year}: {yearCount} sessions.',
  'formations.calendarPageSummary': '{start}-{end} of {total}',
  'formations.previousPage': 'Previous page',
  'formations.nextPage': 'Next page',
  'formations.noCalendarSessions':
      'Training sessions will appear here after a planning import.',
  'formations.noSessionsForDay': 'No session scheduled for this day.',
  'formations.noSessionsForMonth': 'No session scheduled for this month.',
  'formations.calendarReady': 'ready',
  'formations.calendarMissing': 'contacts',
  'formations.calendarPlanned': 'planned',
  'formations.unknownModule': 'Training session',
  'formations.locationMissing': 'Location missing',
  'formations.participantsShort': 'participants',
  'formations.candidatesPlannedShort': 'candidates planned',
  'formations.sessionDetails': 'Session details',
  'formations.sessionDate': 'Date',
  'formations.sessionLocation': 'Location',
  'formations.sessionTrainer': 'Trainer',
  'formations.sessionSchedule': 'Schedule',
  'formations.sessionCode': 'Session code',
  'formations.noSessionParticipants':
      'No detailed participants are linked to this session yet.',
  'formations.unknownParticipant': 'Unnamed participant',
  'formations.residenceMissing': 'Residence missing',
  'formations.matriculeShort': 'Mat.',
  'formations.reviewBeforeSend': 'Review before send',
  'formations.reviewBeforeSendHint':
      'Generated training emails stay blocked until you review, edit, and approve them.',
  'formations.generateDrafts': 'Generate training drafts',
  'formations.runAutomation': 'Run automation',
  'formations.automationSettings': 'Automation settings',
  'formations.automationSettingsSubtitle':
      'Choose how training emails are prepared after a planning import.',
  'formations.autoRunAfterImport': 'Prepare drafts after import',
  'formations.autoRunAfterImportHint':
      'New planning files can create review-ready drafts automatically.',
  'formations.defaultEmailType': 'Default email type',
  'formations.emailTypeAuto': 'Choose automatically',
  'formations.emailTypeAwareness': 'Awareness email',
  'formations.emailTypeConfirmation': 'Training confirmation',
  'formations.includePopulation': 'Include participant list',
  'formations.includePopulationHint':
      'Add the target population table in generated messages.',
  'formations.maxDraftsPerRun': 'Maximum drafts per run',
  'formations.saveAutomationSettings': 'Save settings',
  'formations.importReady': 'ready',
  'formations.waitingImport': 'waiting',
  'formations.waitingReview': 'Review',
  'formations.approved': 'Approved',
  'formations.blocked': 'Blocked',
  'formations.sent': 'sent',
  'formations.draftsToReview': 'Responsible emails to review',
  'formations.responsibleRecipient': 'Responsible',
  'formations.noResponsibleRecipient': 'No responsible recipient yet',
  'formations.noDrafts':
      'No drafts yet. Import a planning file, then generate training emails.',
  'formations.filterAll': 'All',
  'formations.filterReview': 'Review',
  'formations.filterApproved': 'Approved',
  'formations.filterSent': 'Sent',
  'formations.filterBlocked': 'Blocked',
  'formations.filterRejected': 'Rejected',
  'formations.filterByType': 'Email type',
  'formations.filterAllTypes': 'All email types',
  'formations.sendHistory': 'Outlook sent messages',
  'formations.noSendHistory':
      'Messages sent manually from Outlook will appear here.',
  'formations.sentTo': 'To',
  'formations.sentAt': 'Sent at',
  'formations.contactsToComplete': 'Responsible contacts to complete',
  'formations.contactReviewTitle': 'Responsible matching review',
  'formations.contactReviewSubtitle':
      'Check RH/DR/DC responsible staff matching before preparing drafts.',
  'formations.contactReviewReady':
      'All responsible recipients look ready. You can still open a contact to correct it.',
  'formations.contactReviewMatched': 'Matched',
  'formations.contactReviewNameMatch': 'Check',
  'formations.contactReviewMissing': 'Missing',
  'formations.contactReviewEdit': 'Review contact',
  'formations.contactReviewNoEmail': 'No email yet',
  'formations.contactMatchMissing': 'missing',
  'formations.contactMatchMatricule': 'matricule',
  'formations.contactMatchName': 'name match',
  'formations.contactMatchPlanning': 'planning',
  'formations.contactMatchReview': 'review',
  'formations.noSubject': '(No subject)',
  'formations.reviewDraft': 'Review draft',
  'formations.subject': 'Subject',
  'formations.message': 'Message',
  'formations.reject': 'Reject',
  'formations.save': 'Save',
  'formations.markSent': 'Mark as sent',
  'formations.statusApproved': 'approved',
  'formations.statusEdited': 'edited',
  'formations.statusNeedsContacts': 'contacts',
  'formations.statusRejected': 'rejected',
  'formations.statusSent': 'sent',
  'formations.statusError': 'error',
  'formations.statusWaiting': 'review',
  'formations.workflow': 'Workflow',
  'formations.stepImport': 'Import sessions and candidates',
  'formations.stepValidate': 'Check RH/DR/DC responsible staff',
  'formations.stepDraft': 'Prepare French Outlook emails',
  'formations.stepSend': 'Review and mark as sent',
  'formations.emptyTitle': 'No planning imported',
  'formations.emptySubtitle':
      'Sessions, participants, drafts, and send history will appear after the first import.',
  'date.monday': 'Monday',
  'date.tuesday': 'Tuesday',
  'date.wednesday': 'Wednesday',
  'date.thursday': 'Thursday',
  'date.friday': 'Friday',
  'date.saturday': 'Saturday',
  'date.sunday': 'Sunday',
  'date.jan': 'Jan',
  'date.feb': 'Feb',
  'date.mar': 'Mar',
  'date.apr': 'Apr',
  'date.may': 'May',
  'date.jun': 'Jun',
  'date.jul': 'Jul',
  'date.aug': 'Aug',
  'date.sep': 'Sep',
  'date.oct': 'Oct',
  'date.nov': 'Nov',
  'date.dec': 'Dec',
  'review.title': 'Review replies',
  'review.subtitle': 'Check suggested replies before they are sent.',
  'review.urgent': 'urgent',
  'review.ready': 'ready',
  'review.readyToSend': 'ready to send',
  'filter.all': 'All',
  'filter.ready': 'Ready',
  'filter.urgent': 'Urgent',
  'filter.needsEdit': 'Needs edit',
  'assistant.title': 'Ask the assistant',
  'assistant.working': 'Working on your request',
  'assistant.ready': 'Ready for email tasks',
  'assistant.unreachable':
      'I could not reach the assistant. Check the backend services and try again.',
  'assistant.confirmed': 'Action confirmed successfully.',
  'assistant.cancelled': 'Action cancelled.',
  'assistant.unreadSummary': 'Unread summary',
  'assistant.urgentEmails': 'Urgent emails',
  'assistant.classifyInbox': 'Classify inbox',
  'assistant.reviewQueue': 'Review queue',
  'assistant.promptUnread': 'Read and summarize my latest unread email',
  'assistant.promptUrgent': 'Show me my urgent emails',
  'assistant.promptClassify': 'Classify my inbox',
  'assistant.promptReview': 'What emails are ready for review?',
  'assistant.thinking': 'Thinking',
  'assistant.inputHint': 'Ask about your emails...',
  'assistant.emptyTitle': 'What should we handle?',
  'assistant.emptySubtitle':
      'Ask for summaries, priorities, draft replies, or review queue updates.',
  'assistant.summarizeLatest': 'Summarize latest',
  'assistant.findUrgent': 'Find urgent',
  'assistant.confirmAction': 'Confirm action',
  'assistant.confirm': 'Confirm',
  'today.title': 'Today',
  'today.subtitle': 'Follow what happened with your emails today.',
  'today.previousDay': 'Previous day',
  'today.waitingReview': 'waiting for review',
  'today.yesterday': 'Yesterday',
  'today.refreshHint': 'Pull down to refresh the activity timeline.',
  'today.emptyAll': 'No activity for this day',
  'today.emptySent': 'No sent replies',
  'today.emptyReview': 'Nothing waiting for review',
  'today.emptyLow': 'No low-priority emails',
  'filter.sent': 'Sent',
  'filter.review': 'Review',
  'filter.low': 'Low',
  'bulk.campaign': 'Campaign',
  'bulk.recipients': 'Recipients',
  'bulk.added': 'added',
  'bulk.preparing': 'Preparing your drafts',
  'bulk.generate': 'Generate drafts',
  'bulk.previewEdit': 'Preview and edit',
  'bulk.enterCampaign': 'Please enter a campaign topic.',
  'bulk.addRecipient': 'Please add at least one recipient.',
  'bulk.generateFirst': 'Generate drafts first, then preview and edit them.',
  'bulk.generatedCount': '{count} emails generated successfully.',
  'bulk.sentCount': 'Group send completed: {sent}/{total} sent.',
  'bulk.writeIn': 'Write in {language}.',
  'bulk.tone': 'Tone: {tone}.',
  'bulk.length': 'Length: {length}.',
  'bulk.personalize':
      'Personalize each draft using the recipient name, role, and context.',
  'bulk.keepSubject': 'Keep the subject clear and specific.',
  'bulk.hideTools': 'Do not mention AI, automation, or internal tools.',
  'bulk.campaignTopic': 'Campaign topic',
  'bulk.draftsLabel': 'Drafts',
  'bulk.sending': 'Sending',
  'bulk.send': 'Send',
  'bulk.subject': 'Subject',
  'bulk.message': 'Message',
  'bulk.draftStyle': 'Draft style',
  'bulk.toneLabel': 'Tone',
  'bulk.lengthLabel': 'Length',
  'bulk.languageLabel': 'Language',
  'bulk.toneProfessional': 'Professional',
  'bulk.toneFriendly': 'Friendly',
  'bulk.toneDirect': 'Direct',
  'bulk.lengthShort': 'Short',
  'bulk.lengthDetailed': 'Detailed',
  'bulk.addRecipientTitle': 'Add recipient',
  'bulk.name': 'Name',
  'bulk.email': 'Email',
  'bulk.role': 'Role',
  'bulk.defaultRole': 'Recipient',
  'bulk.cancel': 'Cancel',
  'bulk.add': 'Add',
  'bulk.headerTitle': 'Group drafts',
  'bulk.headerSubtitle': 'Prepare personalized messages for several people.',
  'bulk.draftsReady': '{count} drafts ready',
  'bulk.progressTitle': 'Preparing personalized drafts',
  'bulk.progressSubtitle':
      'This can take a little while for {count} recipients. You can stay on this screen while we prepare them.',
  'bulk.removeRecipient': 'Remove recipient',
  'notifications.title': 'Notifications',
  'notifications.subtitle': 'Your review queue and recent email activity.',
  'notifications.updated': 'Updated',
  'notifications.needsEdit': 'needs edit',
  'notifications.emptyTitle': 'Nothing needs attention',
  'notifications.emptySubtitle':
      'Replies ready for review, urgent emails, and recent sent activity will appear here.',
};

const Map<String, String> _french = {
  'language.title': 'Choisissez votre langue',
  'language.subtitle':
      'Vous pourrez la modifier plus tard dans les paramètres. Les brouillons utiliseront cette langue par défaut.',
  'language.english': 'Anglais',
  'language.french': 'Français',
  'language.continue': 'Continuer',
  'nav.home': 'Accueil',
  'nav.today': 'Aujourd’hui',
  'nav.review': 'Revue',
  'nav.profile': 'Profil',
  'common.loading': 'Chargement...',
  'common.notAvailable': 'Non disponible',
  'common.back': 'Retour',
  'common.close': 'Fermer',
  'auth.signInTitle': 'Connectez-vous à votre boîte intelligente',
  'auth.signInSubtitle':
      'Connectez Outlook pour organiser vos messages, préparer des brouillons sûrs et garder chaque action sous votre contrôle.',
  'auth.connecting': 'Connexion...',
  'auth.continueOutlook': 'Continuer avec Outlook',
  'auth.errorOutlook':
      'Impossible de se connecter avec Outlook. Veuillez réessayer.',
  'onboarding.skip': 'Passer',
  'onboarding.openAssistant': 'Ouvrir l’assistant',
  'onboarding.getStarted': 'Commencer',
  'onboarding.connected': 'Outlook connecté',
  'onboarding.primary': '12 principaux',
  'onboarding.priority': '5 prioritaires',
  'onboarding.connectTitle': 'Connectez votre boîte mail',
  'onboarding.connectDescription':
      'Laissez TT Mail Assistant classer, prioriser et préparer des réponses avant que les emails ne vous submergent.',
  'onboarding.reviewProtected': 'Revue protégée',
  'onboarding.urgentHeld': 'Urgents retenus',
  'onboarding.draftChecked': 'Brouillon vérifié',
  'onboarding.controlTitle': 'Gardez le contrôle',
  'onboarding.controlDescription':
      'Les réponses urgentes ou incertaines attendent votre validation, tandis que les emails simples avancent discrètement.',
  'onboarding.repliesReady': 'Réponses prêtes',
  'onboarding.drafts': '3 brouillons',
  'onboarding.approve': 'Valider en un geste',
  'onboarding.answerTitle': 'Répondez plus vite',
  'onboarding.answerDescription':
      'Validez, modifiez ou ignorez les brouillons IA depuis un espace mobile clair, pensé pour le tri quotidien.',
  'settings.title': 'Paramètres',
  'settings.subtitle': 'Gérez votre compte et vos préférences email.',
  'settings.emailHandling': 'Traitement des emails',
  'settings.preferences': 'Préférences',
  'settings.appLanguage': 'Langue de l’application',
  'settings.replyLanguage': 'Langue des réponses',
  'settings.replyLanguageSubtitle': 'Rédiger les brouillons dans cette langue.',
  'settings.prepareReplies': 'Préparer les réponses automatiquement',
  'settings.prepareRepliesOn':
      'Les nouveaux emails non lus deviennent des brouillons à vérifier.',
  'settings.prepareRepliesOff':
      'Les nouveaux emails attendront que cette option soit réactivée.',
  'settings.notifications': 'Notifications',
  'settings.notificationsSubtitle':
      'Recevoir une alerte lorsqu’une réponse est prête à vérifier.',
  'settings.dailySummary': 'Résumé quotidien',
  'settings.dailySummarySubtitle':
      'Recevoir un court résumé des emails traités.',
  'settings.darkMode': 'Mode sombre',
  'settings.darkModeSubtitle': 'Utiliser une apparence plus sombre.',
  'settings.outlookConnected': 'Outlook connecté',
  'settings.signOut': 'Déconnexion',
  'settings.signOutTitle': 'Se déconnecter ?',
  'settings.signOutMessage': 'Vous devrez reconnecter votre compte Outlook.',
  'settings.cancel': 'Annuler',
  'settings.signOutAction': 'Se déconnecter',
  'settings.user': 'Utilisateur',
  'home.error': 'Erreur',
  'home.recentActivity': 'Activité récente',
  'home.noRecentActivity': 'Aucune activité récente',
  'home.processedAppear': 'Les emails traités apparaîtront ici.',
  'home.shortcuts': 'Raccourcis',
  'home.tools': 'Outils',
  'home.goodMorning': 'Bonjour',
  'home.goodAfternoon': 'Bon après-midi',
  'home.goodEvening': 'Bonsoir',
  'home.notifications': 'Notifications',
  'home.repliesNeedReview': 'réponses à vérifier',
  'home.inboxUnderControl': 'Boîte mail sous contrôle',
  'home.openReview':
      'Ouvrez la revue pour vérifier les brouillons avant envoi.',
  'home.newUnreadAppear':
      'Les nouveaux emails non lus apparaîtront ici après traitement.',
  'home.processedToday': 'Emails traités',
  'home.sent': 'Envoyés',
  'home.needReview': 'À vérifier',
  'home.completion': 'Finalisation',
  'home.noSubject': '(Sans objet)',
  'home.unknownSender': 'Expéditeur inconnu',
  'home.reviewReplies': 'Revoir les réponses',
  'home.reviewRepliesShortcut': 'Vérifier les réponses suggérées avant envoi.',
  'home.groupDrafts': 'Brouillons groupés',
  'home.groupDraftsShortcut':
      'Préparer le même message pour plusieurs destinataires.',
  'home.formations': 'Formations',
  'home.formationsShortcut':
      'Importer le planning et préparer les emails de formation.',
  'formations.title': 'Formations',
  'formations.subtitle': 'Planning, participants et brouillons Outlook.',
  'formations.activePlan': 'Planning courant prêt',
  'formations.activePlanHint':
      'Continuez depuis l’étape qui demande votre attention.',
  'formations.noActivePlan': 'Commencer par un planning',
  'formations.noActivePlanHint':
      'Importez le planning Excel du mois pour démarrer.',
  'formations.workflowTitle': 'Parcours formation',
  'formations.imports': 'imports',
  'formations.total': 'total',
  'formations.toCheck': 'à vérifier',
  'formations.importStepTitle': 'Planning des sessions',
  'formations.importStepSubtitle':
      'Importer le fichier Excel des sessions de formation.',
  'formations.contactsStepTitle': 'Responsables',
  'formations.contactsStepSubtitle': 'Rechercher dans l’annuaire RH/DR/DC.',
  'formations.calendarStepTitle': 'Calendrier',
  'formations.calendarStepSubtitle':
      'Vérifier les sessions par date de formation.',
  'formations.draftsStepTitle': 'Brouillons',
  'formations.draftsStepSubtitle':
      'Générer, vérifier et marquer comme envoyés.',
  'formations.historyStepTitle': 'Emails envoyés',
  'formations.historyStepSubtitle': 'Lire les éléments envoyés Outlook.',
  'formations.importPageTitle': 'Importer les formations',
  'formations.importPageSubtitle':
      'Ajoutez le planning des sessions, puis la liste des participants.',
  'formations.calendarPageTitle': 'Calendrier des formations',
  'formations.calendarPageSubtitle': 'Parcourir les sessions par jour.',
  'formations.draftsPageTitle': 'Vérification des brouillons',
  'formations.draftsPageSubtitle':
      'Vérifier les emails de confirmation destinés aux responsables avant envoi.',
  'formations.contactsPageTitle': 'Responsables',
  'formations.contactsPageSubtitle':
      'Rechercher et consulter l’annuaire des responsables.',
  'formations.historyPageTitle': 'Emails envoyés',
  'formations.historyPageSubtitle':
      'Consulter les messages récents dans les éléments envoyés Outlook.',
  'formations.uploadTitle': 'Fichier planning des sessions',
  'formations.uploadSubtitle':
      'Importez les fichiers Excel pour détecter les sessions, participants, résidences et responsables.',
  'formations.uploadAction': 'Ajouter le planning',
  'formations.uploadNext':
      'L’import du planning sera connecté à l’étape suivante.',
  'formations.refresh': 'Actualiser',
  'formations.pickError':
      'Impossible de lire les fichiers de planning sélectionnés.',
  'formations.uploadLimit': 'Seuls les 5 premiers fichiers ont été retenus.',
  'formations.importDone': 'Planning importé avec succès.',
  'formations.importFeedbackTitle': 'Résultat de l’import',
  'formations.importPreviewTitle': 'Aperçu avant import',
  'formations.importFeedbackClean':
      'Le planning est prêt. Aucun problème bloquant n’a été détecté.',
  'formations.importPreviewClean':
      'Ce planning semble prêt à importer. Rien n’est encore enregistré.',
  'formations.importFeedbackNeedsReview':
      'Le planning est importé, mais certains points demandent votre attention.',
  'formations.importPreviewNeedsReview':
      'Vérifiez ces points avant d’enregistrer le planning.',
  'formations.importNoEmailsDetectedSummary':
      'Les candidats ont été trouvés. Les responsables seront associés par grande résidence.',
  'formations.importPreviewNotSaved':
      'Ceci est seulement un aperçu. Confirmez pour enregistrer le planning et préparer les brouillons si l’automatisation est activée.',
  'formations.confirmImport': 'Importer le planning',
  'formations.feedbackFiles': 'Fichiers',
  'formations.feedbackMissingEmails': 'Responsables manquants',
  'formations.feedbackEmailsDetected': 'Responsables détectés',
  'formations.feedbackNoEmailsDetected':
      'Les emails des candidats ne sont pas nécessaires. Les brouillons sont préparés pour les responsables RH/DR/DC selon la résidence.',
  'formations.feedbackAutomationRan':
      'L’automatisation a préparé {generated} brouillons et ignoré {skipped} doublons.',
  'formations.feedbackAutomationSkipped':
      'La préparation automatique est désactivée. Vous pourrez la lancer plus tard.',
  'formations.feedbackIssueCount':
      '{warnings} alertes et {errors} erreurs ont été détectées.',
  'formations.feedbackFilesTitle': 'Fichiers importés',
  'formations.feedbackFileSessions': '{count} sessions trouvées',
  'formations.importStatusOk': 'prêt',
  'formations.importStatusReview': 'à vérifier',
  'formations.importStatusError': 'erreur',
  'formations.importStatusUnknown': 'inconnu',
  'formations.draftsDone': 'Brouillons prêts pour vérification.',
  'formations.automationDone':
      'Automatisation terminée. Brouillons prêts pour vérification.',
  'formations.contactsTitle': 'Annuaire des responsables',
  'formations.contactsSubtitle':
      'Les responsables sont chargés depuis la base de données.',
  'formations.candidatesTitle': 'Liste des participants',
  'formations.candidatesSubtitle':
      'Importez le fichier Excel ou CSV des participants par session.',
  'formations.contactsUpload': 'Importer les contacts',
  'formations.contactsImported': 'Contacts responsables importés et appliqués.',
  'formations.responsableSearch': 'Rechercher',
  'formations.responsableSearchHint':
      'Rechercher par nom, fonction ou résidence',
  'formations.noResponsables': 'Aucun responsable trouvé.',
  'formations.contactPickError':
      'Impossible de lire les fichiers contacts sélectionnés.',
  'formations.fixContact': 'Corriger le responsable',
  'formations.emailAddress': 'Email du responsable',
  'formations.invalidEmail': 'Saisissez une adresse email valide.',
  'formations.saveContact': 'Enregistrer le contact',
  'formations.monthPlan': 'Vue du mois',
  'formations.sessions': 'Sessions',
  'formations.participants': 'Participants',
  'formations.responsibles': 'Responsables',
  'formations.toReview': 'À vérifier',
  'formations.drafts': 'Brouillons',
  'formations.missing': 'Données manquantes',
  'formations.missingResponsibleEmails': 'Responsables manquants',
  'formations.calendarTitle': 'Calendrier des formations',
  'formations.calendarSubtitle':
      '{count} sessions trouvées pour le mois sélectionné.',
  'formations.calendarYear': 'Année',
  'formations.calendarMonth': 'Mois',
  'formations.pickMonth': 'Choisir le mois',
  'formations.previousMonth': 'Mois précédent',
  'formations.nextMonth': 'Mois suivant',
  'formations.calendarSelectionSummary':
      '{month} : {monthCount} sessions. {year} : {yearCount} sessions.',
  'formations.calendarPageSummary': '{start}-{end} sur {total}',
  'formations.previousPage': 'Page précédente',
  'formations.nextPage': 'Page suivante',
  'formations.noCalendarSessions':
      'Les sessions de formation apparaîtront ici après l’import du planning.',
  'formations.noSessionsForDay': 'Aucune session programmée ce jour.',
  'formations.noSessionsForMonth': 'Aucune session programmée ce mois.',
  'formations.calendarReady': 'prêt',
  'formations.calendarMissing': 'contacts',
  'formations.calendarPlanned': 'prévu',
  'formations.unknownModule': 'Session de formation',
  'formations.locationMissing': 'Lieu manquant',
  'formations.participantsShort': 'participants',
  'formations.candidatesPlannedShort': 'candidats prévus',
  'formations.sessionDetails': 'Détails de la session',
  'formations.sessionDate': 'Date',
  'formations.sessionLocation': 'Lieu',
  'formations.sessionTrainer': 'Formateur',
  'formations.sessionSchedule': 'Horaire',
  'formations.sessionCode': 'Code session',
  'formations.noSessionParticipants':
      'Aucun participant détaillé n’est lié à cette session pour le moment.',
  'formations.unknownParticipant': 'Participant sans nom',
  'formations.residenceMissing': 'Résidence manquante',
  'formations.matriculeShort': 'Mat.',
  'formations.reviewBeforeSend': 'Vérifier avant envoi',
  'formations.reviewBeforeSendHint':
      'Les emails de formation restent bloqués jusqu’à vérification, modification et validation.',
  'formations.generateDrafts': 'Générer les brouillons',
  'formations.runAutomation': 'Lancer l’automatisation',
  'formations.automationSettings': 'Paramètres d’automatisation',
  'formations.automationSettingsSubtitle':
      'Choisissez comment préparer les emails après l’import du planning.',
  'formations.autoRunAfterImport': 'Préparer après import',
  'formations.autoRunAfterImportHint':
      'Les nouveaux plannings peuvent créer automatiquement des brouillons à vérifier.',
  'formations.defaultEmailType': 'Type d’email par défaut',
  'formations.emailTypeAuto': 'Choix automatique',
  'formations.emailTypeAwareness': 'Email de sensibilisation',
  'formations.emailTypeConfirmation': 'Confirmation de présence',
  'formations.includePopulation': 'Inclure la liste des participants',
  'formations.includePopulationHint':
      'Ajouter le tableau de la population cible dans les messages générés.',
  'formations.maxDraftsPerRun': 'Nombre maximal de brouillons par lancement',
  'formations.saveAutomationSettings': 'Enregistrer',
  'formations.importReady': 'prêt',
  'formations.waitingImport': 'en attente',
  'formations.waitingReview': 'À vérifier',
  'formations.approved': 'Validés',
  'formations.blocked': 'Bloqués',
  'formations.sent': 'envoyés',
  'formations.draftsToReview': 'Emails responsables à vérifier',
  'formations.responsibleRecipient': 'Responsable',
  'formations.noResponsibleRecipient': 'Aucun responsable associé',
  'formations.noDrafts':
      'Aucun brouillon. Importez un planning, puis générez les emails de formation.',
  'formations.filterAll': 'Tous',
  'formations.filterReview': 'À vérifier',
  'formations.filterApproved': 'Validés',
  'formations.filterSent': 'Envoyés',
  'formations.filterBlocked': 'Bloqués',
  'formations.filterRejected': 'Refusés',
  'formations.filterByType': 'Type d’email',
  'formations.filterAllTypes': 'Tous les types',
  'formations.sendHistory': 'Messages envoyés Outlook',
  'formations.noSendHistory':
      'Les messages envoyés manuellement depuis Outlook apparaîtront ici.',
  'formations.sentTo': 'À',
  'formations.sentAt': 'Envoyé le',
  'formations.contactsToComplete': 'Responsables à compléter',
  'formations.contactReviewTitle': 'Vérification des responsables',
  'formations.contactReviewSubtitle':
      'Vérifiez l’association des responsables RH/DR/DC avant de préparer les brouillons.',
  'formations.contactReviewReady':
      'Tous les responsables semblent prêts. Vous pouvez ouvrir un contact pour le corriger.',
  'formations.contactReviewMatched': 'Associés',
  'formations.contactReviewNameMatch': 'À vérifier',
  'formations.contactReviewMissing': 'Manquants',
  'formations.contactReviewEdit': 'Vérifier le contact',
  'formations.contactReviewNoEmail': 'Aucun email',
  'formations.contactMatchMissing': 'manquant',
  'formations.contactMatchMatricule': 'matricule',
  'formations.contactMatchName': 'nom',
  'formations.contactMatchPlanning': 'planning',
  'formations.contactMatchReview': 'revue',
  'formations.noSubject': '(Sans objet)',
  'formations.reviewDraft': 'Vérifier le brouillon',
  'formations.subject': 'Objet',
  'formations.message': 'Message',
  'formations.reject': 'Refuser',
  'formations.save': 'Enregistrer',
  'formations.markSent': 'Marquer comme envoyé',
  'formations.statusApproved': 'validé',
  'formations.statusEdited': 'modifié',
  'formations.statusNeedsContacts': 'contacts',
  'formations.statusRejected': 'refusé',
  'formations.statusSent': 'envoyé',
  'formations.statusError': 'erreur',
  'formations.statusWaiting': 'à vérifier',
  'formations.workflow': 'Traitement',
  'formations.stepImport': 'Importer les sessions et les participants',
  'formations.stepValidate': 'Vérifier les responsables RH/DR/DC',
  'formations.stepDraft': 'Préparer les emails Outlook en français',
  'formations.stepSend': 'Revoir et marquer comme envoyé',
  'formations.emptyTitle': 'Aucun planning importé',
  'formations.emptySubtitle':
      'Les sessions, participants, brouillons et historiques d’envoi apparaîtront après le premier import.',
  'date.monday': 'Lundi',
  'date.tuesday': 'Mardi',
  'date.wednesday': 'Mercredi',
  'date.thursday': 'Jeudi',
  'date.friday': 'Vendredi',
  'date.saturday': 'Samedi',
  'date.sunday': 'Dimanche',
  'date.jan': 'Jan',
  'date.feb': 'Fév',
  'date.mar': 'Mar',
  'date.apr': 'Avr',
  'date.may': 'Mai',
  'date.jun': 'Juin',
  'date.jul': 'Juil',
  'date.aug': 'Août',
  'date.sep': 'Sep',
  'date.oct': 'Oct',
  'date.nov': 'Nov',
  'date.dec': 'Déc',
  'review.title': 'Revoir les réponses',
  'review.subtitle': 'Vérifiez les réponses suggérées avant leur envoi.',
  'review.urgent': 'urgent',
  'review.ready': 'prêtes',
  'review.readyToSend': 'prêtes à envoyer',
  'filter.all': 'Tous',
  'filter.ready': 'Prêtes',
  'filter.urgent': 'Urgentes',
  'filter.needsEdit': 'À modifier',
  'assistant.title': 'Demander à l’assistant',
  'assistant.working': 'Traitement de votre demande',
  'assistant.ready': 'Prêt pour les tâches email',
  'assistant.unreachable':
      'Impossible de joindre l’assistant. Vérifiez les services backend, puis réessayez.',
  'assistant.confirmed': 'Action confirmée avec succès.',
  'assistant.cancelled': 'Action annulée.',
  'assistant.unreadSummary': 'Résumé des emails non lus',
  'assistant.urgentEmails': 'Emails urgents',
  'assistant.classifyInbox': 'Classer la boîte mail',
  'assistant.reviewQueue': 'File de revue',
  'assistant.promptUnread': 'Lis et résume mon dernier email non lu',
  'assistant.promptUrgent': 'Montre-moi mes emails urgents',
  'assistant.promptClassify': 'Classe ma boîte mail',
  'assistant.promptReview': 'Quels emails sont prêts à être vérifiés ?',
  'assistant.thinking': 'Réflexion',
  'assistant.inputHint': 'Posez une question sur vos emails...',
  'assistant.emptyTitle': 'Que voulez-vous traiter ?',
  'assistant.emptySubtitle':
      'Demandez des résumés, priorités, brouillons ou mises à jour de la revue.',
  'assistant.summarizeLatest': 'Résumer le dernier',
  'assistant.findUrgent': 'Trouver les urgents',
  'assistant.confirmAction': 'Confirmer l’action',
  'assistant.confirm': 'Confirmer',
  'today.title': 'Aujourd’hui',
  'today.subtitle': 'Suivez ce qui s’est passé avec vos emails aujourd’hui.',
  'today.previousDay': 'Jour précédent',
  'today.waitingReview': 'en attente de revue',
  'today.yesterday': 'Hier',
  'today.refreshHint': 'Tirez vers le bas pour actualiser la chronologie.',
  'today.emptyAll': 'Aucune activité pour ce jour',
  'today.emptySent': 'Aucune réponse envoyée',
  'today.emptyReview': 'Rien en attente de revue',
  'today.emptyLow': 'Aucun email de faible priorité',
  'filter.sent': 'Envoyés',
  'filter.review': 'Revue',
  'filter.low': 'Faible',
  'bulk.campaign': 'Campagne',
  'bulk.recipients': 'Destinataires',
  'bulk.added': 'ajoutés',
  'bulk.preparing': 'Préparation de vos brouillons',
  'bulk.generate': 'Générer les brouillons',
  'bulk.previewEdit': 'Prévisualiser et modifier',
  'bulk.enterCampaign': 'Veuillez saisir le sujet de la campagne.',
  'bulk.addRecipient': 'Veuillez ajouter au moins un destinataire.',
  'bulk.generateFirst':
      'Générez les brouillons avant de les prévisualiser et les modifier.',
  'bulk.generatedCount': '{count} emails générés avec succès.',
  'bulk.sentCount': 'Envoi groupé terminé : {sent}/{total} envoyés.',
  'bulk.writeIn': 'Rédiger en {language}.',
  'bulk.tone': 'Ton : {tone}.',
  'bulk.length': 'Longueur : {length}.',
  'bulk.personalize':
      'Personnaliser chaque brouillon avec le nom, le rôle et le contexte du destinataire.',
  'bulk.keepSubject': 'Garder un objet clair et précis.',
  'bulk.hideTools':
      'Ne pas mentionner l’IA, l’automatisation ou les outils internes.',
  'bulk.campaignTopic': 'Sujet de la campagne',
  'bulk.draftsLabel': 'Brouillons',
  'bulk.sending': 'Envoi',
  'bulk.send': 'Envoyer',
  'bulk.subject': 'Objet',
  'bulk.message': 'Message',
  'bulk.draftStyle': 'Style du brouillon',
  'bulk.toneLabel': 'Ton',
  'bulk.lengthLabel': 'Longueur',
  'bulk.languageLabel': 'Langue',
  'bulk.toneProfessional': 'Professionnel',
  'bulk.toneFriendly': 'Chaleureux',
  'bulk.toneDirect': 'Direct',
  'bulk.lengthShort': 'Court',
  'bulk.lengthDetailed': 'Détaillé',
  'bulk.addRecipientTitle': 'Ajouter un destinataire',
  'bulk.name': 'Nom',
  'bulk.email': 'Email',
  'bulk.role': 'Rôle',
  'bulk.defaultRole': 'Destinataire',
  'bulk.cancel': 'Annuler',
  'bulk.add': 'Ajouter',
  'bulk.headerTitle': 'Brouillons groupés',
  'bulk.headerSubtitle':
      'Préparer des messages personnalisés pour plusieurs personnes.',
  'bulk.draftsReady': '{count} brouillons prêts',
  'bulk.progressTitle': 'Préparation des brouillons personnalisés',
  'bulk.progressSubtitle':
      'Cela peut prendre un peu de temps pour {count} destinataires. Vous pouvez rester sur cet écran pendant la préparation.',
  'bulk.removeRecipient': 'Supprimer le destinataire',
  'notifications.title': 'Notifications',
  'notifications.subtitle': 'Votre file de revue et l’activité récente.',
  'notifications.updated': 'Mis à jour',
  'notifications.needsEdit': 'à modifier',
  'notifications.emptyTitle': 'Rien ne demande votre attention',
  'notifications.emptySubtitle':
      'Les réponses prêtes, emails urgents et envois récents apparaîtront ici.',
};
