import 'package:flutter/widgets.dart';
import 'package:tt_mail_assistant/core/di/di.dart';
import 'package:tt_mail_assistant/core/localization/app_language_controller.dart';

class AppLocalizations {
  const AppLocalizations(this.language);

  final AppLanguage language;

  bool get isFrench => language == AppLanguage.french;

  String t(String key) {
    if (!isFrench) return _english[key] ?? key;
    return _french[key] ?? _english[key] ?? key;
  }

  String languageName(AppLanguage value) {
    return value == AppLanguage.french ? 'Français' : 'English';
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n {
    return AppLocalizations(getIt<AppLanguageController>().language);
  }
}

const Map<String, String> _english = {
  'language.title': 'Choose your language',
  'language.subtitle':
      'You can change this later from Settings. The assistant will use the same language for drafts by default.',
  'language.english': 'English',
  'language.french': 'Français',
  'language.continue': 'Continue',
  'nav.home': 'Home',
  'nav.today': 'Today',
  'nav.review': 'Review',
  'nav.profile': 'Profile',
  'auth.signInTitle': 'Sign in to your intelligent inbox',
  'auth.signInSubtitle':
      'Connect Outlook to classify messages, prepare safe drafts, and keep every action under your control.',
  'auth.connecting': 'Connecting...',
  'auth.continueOutlook': 'Continue with Outlook',
  'auth.errorOutlook': 'Unable to sign in with Outlook. Please try again.',
  'onboarding.skip': 'Skip',
  'onboarding.openAssistant': 'Open assistant',
  'onboarding.getStarted': 'Get started',
  'onboarding.connected': 'Outlook connected',
  'onboarding.primary': '12 primary',
  'onboarding.priority': '5 priority',
  'onboarding.connectTitle': 'Connect your inbox',
  'onboarding.connectDescription':
      'Let TT Mail Assistant classify, prioritize, and draft replies before email noise reaches you.',
  'onboarding.reviewProtected': 'Review protected',
  'onboarding.urgentHeld': 'Urgent held',
  'onboarding.draftChecked': 'Draft checked',
  'onboarding.controlTitle': 'Keep control',
  'onboarding.controlDescription':
      'Urgent or uncertain replies wait for your review, while safe routine emails move quietly.',
  'onboarding.repliesReady': 'Replies ready',
  'onboarding.drafts': '3 drafts',
  'onboarding.approve': '1 tap approve',
  'onboarding.answerTitle': 'Answer faster',
  'onboarding.answerDescription':
      'Approve, edit, or ignore AI drafts from one calm mobile workspace built for daily triage.',
  'settings.title': 'Settings',
  'settings.subtitle': 'Manage your account and email preferences.',
  'settings.emailHandling': 'Email handling',
  'settings.preferences': 'Preferences',
  'settings.appLanguage': 'App language',
  'settings.replyLanguage': 'Reply language',
  'settings.replyLanguageSubtitle': 'Draft replies in this language.',
  'settings.prepareReplies': 'Prepare replies automatically',
  'settings.prepareRepliesOn':
      'New unread emails are turned into drafts for review.',
  'settings.prepareRepliesOff':
      'New emails will wait until this is turned back on.',
  'settings.notifications': 'Notifications',
  'settings.notificationsSubtitle':
      'Get alerts when a reply is ready to review.',
  'settings.dailySummary': 'Daily summary',
  'settings.dailySummarySubtitle': 'Receive a short recap of handled emails.',
  'settings.darkMode': 'Dark mode',
  'settings.darkModeSubtitle': 'Use the app with a darker appearance.',
  'settings.outlookConnected': 'Outlook connected',
  'settings.signOut': 'Sign out',
  'settings.signOutTitle': 'Sign out?',
  'settings.signOutMessage':
      'You will need to connect your Outlook account again.',
  'settings.cancel': 'Cancel',
  'settings.signOutAction': 'Sign out',
  'settings.user': 'User',
  'common.back': 'Back',
  'common.close': 'Close',
  'home.error': 'Error',
  'home.recentActivity': 'Recent activity',
  'home.noRecentActivity': 'No recent activity',
  'home.processedAppear': 'Processed emails will appear here.',
  'home.shortcuts': 'Shortcuts',
  'home.tools': 'Tools',
  'home.goodMorning': 'Good morning',
  'home.goodAfternoon': 'Good afternoon',
  'home.goodEvening': 'Good evening',
  'home.notifications': 'Notifications',
  'home.repliesNeedReview': 'replies need review',
  'home.inboxUnderControl': 'Inbox is under control',
  'home.openReview': 'Open Review to check drafts before sending.',
  'home.newUnreadAppear':
      'New unread emails will appear here after the agents process them.',
  'home.processedToday': 'Processed today',
  'home.sent': 'Sent',
  'home.needReview': 'Need review',
  'home.completion': 'Completion',
  'home.noSubject': '(No subject)',
  'home.unknownSender': 'Unknown sender',
  'home.reviewReplies': 'Review replies',
  'home.reviewRepliesShortcut': 'Check suggested replies before sending.',
  'home.groupDrafts': 'Group drafts',
  'home.groupDraftsShortcut': 'Prepare the same message for many recipients.',
  'home.formations': 'Formations',
  'home.formationsShortcut': 'Import planning and send training emails.',
  'formations.title': 'Formations',
  'formations.subtitle': 'Planning, participants, and Outlook drafts.',
  'formations.activePlan': 'Current planning is ready',
  'formations.activePlanHint': 'Continue from the step that needs attention.',
  'formations.noActivePlan': 'Start with a planning file',
  'formations.noActivePlanHint': 'Import the monthly Excel planning to begin.',
  'formations.workflowTitle': 'Training workflow',
  'formations.imports': 'imports',
  'formations.toCheck': 'to check',
  'formations.importStepTitle': 'Session planning',
  'formations.importStepSubtitle': 'Import the training session Excel file.',
  'formations.contactsStepTitle': 'Candidates',
  'formations.contactsStepSubtitle': 'Import candidate rows and complete emails.',
  'formations.calendarStepTitle': 'Calendar',
  'formations.calendarStepSubtitle': 'Review sessions by training date.',
  'formations.draftsStepTitle': 'Drafts',
  'formations.draftsStepSubtitle': 'Generate, edit, approve, and send.',
  'formations.historyStepTitle': 'Sent emails',
  'formations.historyStepSubtitle': 'Check Outlook send attempts.',
  'formations.settingsStepTitle': 'Automation',
  'formations.settingsStepSubtitle': 'Adjust draft preparation rules.',
  'formations.importPageTitle': 'Import formations',
  'formations.importPageSubtitle': 'Add the session planning, then the candidate list.',
  'formations.calendarPageTitle': 'Training calendar',
  'formations.calendarPageSubtitle': 'Browse sessions by day.',
  'formations.draftsPageTitle': 'Draft review',
  'formations.draftsPageSubtitle': 'Check every email before sending.',
  'formations.contactsPageTitle': 'Candidates',
  'formations.contactsPageSubtitle': 'Correct missing or uncertain candidate emails.',
  'formations.historyPageTitle': 'Sent emails',
  'formations.historyPageSubtitle': 'Review what was sent from Outlook.',
  'formations.uploadTitle': 'Session planning file',
  'formations.uploadSubtitle':
      'Upload the Excel file that contains the training sessions, dates, locations, cabinets, and trainers.',
  'formations.uploadAction': 'Add session planning',
  'formations.uploadNext':
      'Planning upload will be connected in the next step.',
  'formations.refresh': 'Refresh',
  'formations.pickError': 'Unable to read the selected session planning files.',
  'formations.uploadLimit': 'Only the first 5 files were selected.',
  'formations.importDone': 'Planning imported successfully.',
  'formations.importFeedbackTitle': 'Planning import result',
  'formations.importPreviewTitle': 'Preview planning import',
  'formations.importFeedbackClean':
      'Planning is ready. No blocking issue was found.',
  'formations.importPreviewClean':
      'This planning looks ready to import. Nothing has been saved yet.',
  'formations.importFeedbackNeedsReview':
      'Planning was imported, but a few items need attention.',
  'formations.importPreviewNeedsReview':
      'Review these points before saving the planning.',
  'formations.importNoEmailsDetectedSummary':
      'Candidate rows were found, but no email addresses were detected yet.',
  'formations.importPreviewNotSaved':
      'This is only a preview. Confirm to save the planning and prepare drafts if automation is enabled.',
  'formations.confirmImport': 'Import planning',
  'formations.feedbackFiles': 'Files',
  'formations.feedbackMissingEmails': 'Missing emails',
  'formations.feedbackEmailsDetected': 'Emails detected',
  'formations.feedbackNoEmailsDetected':
      '0 candidate emails detected for now. This is expected if the candidate planning is not completed yet. Import the completed Excel later to prepare and send emails.',
  'formations.feedbackAutomationRan':
      'Automation prepared {generated} drafts and skipped {skipped} existing ones.',
  'formations.feedbackAutomationSkipped':
      'Automatic draft preparation is off. You can run it when ready.',
  'formations.feedbackIssueCount':
      '{warnings} warnings and {errors} errors were found.',
  'formations.feedbackFilesTitle': 'Imported files',
  'formations.feedbackFileSessions': '{count} sessions found',
  'formations.importStatusOk': 'ready',
  'formations.importStatusReview': 'review',
  'formations.importStatusError': 'error',
  'formations.importStatusUnknown': 'unknown',
  'formations.draftsDone': 'Drafts are ready for review.',
  'formations.automationDone':
      'Automation completed. Drafts are ready for review.',
  'formations.contactsTitle': 'Candidate list',
  'formations.contactsSubtitle':
      'Upload the Excel or CSV file that contains matricules, names, residences, RH contacts, and emails when available.',
  'formations.contactsUpload': 'Upload candidates',
  'formations.contactsImported': 'Candidate list imported and applied.',
  'formations.contactPickError': 'Unable to read the selected candidate files.',
  'formations.fixContact': 'Fix contact',
  'formations.emailAddress': 'Email address',
  'formations.invalidEmail': 'Enter a valid email address.',
  'formations.saveContact': 'Save contact',
  'formations.monthPlan': 'Month overview',
  'formations.sessions': 'Sessions',
  'formations.participants': 'Participants',
  'formations.drafts': 'Drafts',
  'formations.missing': 'Missing data',
  'formations.calendarTitle': 'Training calendar',
  'formations.calendarSubtitle':
      '{count} upcoming sessions from this planning.',
  'formations.noCalendarSessions':
      'Training sessions will appear here after a planning import.',
  'formations.noSessionsForDay': 'No session scheduled for this day.',
  'formations.calendarReady': 'ready',
  'formations.calendarMissing': 'contacts',
  'formations.calendarPlanned': 'planned',
  'formations.unknownModule': 'Training session',
  'formations.locationMissing': 'Location missing',
  'formations.participantsShort': 'participants',
  'formations.candidatesPlannedShort': 'candidates planned',
  'formations.reviewBeforeSend': 'Review before send',
  'formations.reviewBeforeSendHint':
      'Generated training emails stay blocked until you review, edit, and approve them.',
  'formations.generateDrafts': 'Generate training drafts',
  'formations.runAutomation': 'Run automation',
  'formations.automationSettings': 'Automation settings',
  'formations.automationSettingsSubtitle':
      'Choose how training emails are prepared after a planning import.',
  'formations.autoRunAfterImport': 'Prepare drafts after import',
  'formations.autoRunAfterImportHint':
      'New planning files can create review-ready drafts automatically.',
  'formations.defaultEmailType': 'Default email type',
  'formations.emailTypeAuto': 'Choose automatically',
  'formations.emailTypeAwareness': 'Awareness email',
  'formations.emailTypeConfirmation': 'Presence confirmation',
  'formations.includePopulation': 'Include participant list',
  'formations.includePopulationHint':
      'Add the target population table in generated messages.',
  'formations.maxDraftsPerRun': 'Maximum drafts per run',
  'formations.saveAutomationSettings': 'Save settings',
  'formations.importReady': 'ready',
  'formations.waitingImport': 'waiting',
  'formations.waitingReview': 'Review',
  'formations.approved': 'Approved',
  'formations.blocked': 'Blocked',
  'formations.sent': 'sent',
  'formations.draftsToReview': 'Drafts to review',
  'formations.noDrafts':
      'No drafts yet. Import a planning file, then generate training emails.',
  'formations.filterAll': 'All',
  'formations.filterReview': 'Review',
  'formations.filterApproved': 'Approved',
  'formations.filterSent': 'Sent',
  'formations.filterBlocked': 'Blocked',
  'formations.filterRejected': 'Rejected',
  'formations.filterByType': 'Email type',
  'formations.filterAllTypes': 'All email types',
  'formations.sendHistory': 'Send history',
  'formations.noSendHistory':
      'Sent and failed Outlook attempts will appear here.',
  'formations.sentTo': 'To',
  'formations.sentAt': 'Sent at',
  'formations.contactsToComplete': 'Candidates to complete',
  'formations.contactReviewTitle': 'Candidate matching review',
  'formations.contactReviewSubtitle':
      'Check missing candidate emails and name-based matches before preparing or sending drafts.',
  'formations.contactReviewReady':
      'All candidate emails look matched. You can still open a candidate to correct it.',
  'formations.contactReviewMatched': 'Matched',
  'formations.contactReviewNameMatch': 'Check',
  'formations.contactReviewMissing': 'Missing',
  'formations.contactReviewEdit': 'Review candidate',
  'formations.contactReviewNoEmail': 'No email yet',
  'formations.contactMatchMissing': 'missing',
  'formations.contactMatchMatricule': 'matricule',
  'formations.contactMatchName': 'name match',
  'formations.contactMatchPlanning': 'planning',
  'formations.contactMatchReview': 'review',
  'formations.noSubject': '(No subject)',
  'formations.noRecipients': 'No recipient yet',
  'formations.reviewDraft': 'Review draft',
  'formations.regenerateDraft': 'Regenerate draft',
  'formations.regenerateAction': 'Regenerate',
  'formations.regenerateWarning':
      'This will replace the current subject, message, and recipients with a fresh generated version.',
  'formations.regenerateDone': 'Draft regenerated. Review it before sending.',
  'formations.recipients': 'Recipients',
  'formations.cc': 'Cc',
  'formations.optional': 'Optional',
  'formations.subject': 'Subject',
  'formations.message': 'Message',
  'formations.reject': 'Reject',
  'formations.save': 'Save',
  'formations.approve': 'Approve',
  'formations.sendWithOutlook': 'Send with Outlook',
  'formations.sendSafetyTitle': 'Confirm before sending',
  'formations.sendSafetyMessage':
      'This message will be sent from Outlook. Check the subject and recipients one last time.',
  'formations.sendSafetyRecipients': 'recipient(s)',
  'formations.sendSafetyCheckbox':
      'I checked the recipients and content, and I want to send this email.',
  'formations.statusApproved': 'approved',
  'formations.statusEdited': 'edited',
  'formations.statusNeedsContacts': 'contacts',
  'formations.statusRejected': 'rejected',
  'formations.statusSent': 'sent',
  'formations.statusError': 'error',
  'formations.statusWaiting': 'review',
  'formations.workflow': 'Workflow',
  'formations.stepImport': 'Import sessions and candidates',
  'formations.stepValidate': 'Validate candidate emails',
  'formations.stepDraft': 'Prepare French Outlook drafts',
  'formations.stepSend': 'Review, edit, and send',
  'formations.emptyTitle': 'No planning imported',
  'formations.emptySubtitle':
      'Sessions, participants, drafts, and send history will appear after the first import.',
  'date.monday': 'Monday',
  'date.tuesday': 'Tuesday',
  'date.wednesday': 'Wednesday',
  'date.thursday': 'Thursday',
  'date.friday': 'Friday',
  'date.saturday': 'Saturday',
  'date.sunday': 'Sunday',
  'date.jan': 'Jan',
  'date.feb': 'Feb',
  'date.mar': 'Mar',
  'date.apr': 'Apr',
  'date.may': 'May',
  'date.jun': 'Jun',
  'date.jul': 'Jul',
  'date.aug': 'Aug',
  'date.sep': 'Sep',
  'date.oct': 'Oct',
  'date.nov': 'Nov',
  'date.dec': 'Dec',
  'review.title': 'Review replies',
  'review.subtitle': 'Check suggested replies before they are sent.',
  'review.urgent': 'urgent',
  'review.ready': 'ready',
  'review.readyToSend': 'ready to send',
  'filter.all': 'All',
  'filter.ready': 'Ready',
  'filter.urgent': 'Urgent',
  'filter.needsEdit': 'Needs edit',
  'assistant.title': 'Ask the assistant',
  'assistant.working': 'Working on your request',
  'assistant.ready': 'Ready for email tasks',
  'assistant.unreachable':
      'I could not reach the assistant. Check the backend services and try again.',
  'assistant.confirmed': 'Action confirmed successfully.',
  'assistant.cancelled': 'Action cancelled.',
  'assistant.unreadSummary': 'Unread summary',
  'assistant.urgentEmails': 'Urgent emails',
  'assistant.classifyInbox': 'Classify inbox',
  'assistant.reviewQueue': 'Review queue',
  'assistant.promptUnread': 'Read and summarize my latest unread email',
  'assistant.promptUrgent': 'Show me my urgent emails',
  'assistant.promptClassify': 'Classify my inbox',
  'assistant.promptReview': 'What emails are ready for review?',
  'assistant.thinking': 'Thinking',
  'assistant.inputHint': 'Ask about your emails...',
  'assistant.emptyTitle': 'What should we handle?',
  'assistant.emptySubtitle':
      'Ask for summaries, priorities, draft replies, or review queue updates.',
  'assistant.summarizeLatest': 'Summarize latest',
  'assistant.findUrgent': 'Find urgent',
  'assistant.confirmAction': 'Confirm action',
  'assistant.confirm': 'Confirm',
  'today.title': 'Today',
  'today.subtitle': 'Follow what happened with your emails today.',
  'today.previousDay': 'Previous day',
  'today.waitingReview': 'waiting for review',
  'today.yesterday': 'Yesterday',
  'today.refreshHint': 'Pull down to refresh the activity timeline.',
  'today.emptyAll': 'No activity for this day',
  'today.emptySent': 'No sent replies',
  'today.emptyReview': 'Nothing waiting for review',
  'today.emptyLow': 'No low-priority emails',
  'filter.sent': 'Sent',
  'filter.review': 'Review',
  'filter.low': 'Low',
  'bulk.campaign': 'Campaign',
  'bulk.recipients': 'Recipients',
  'bulk.added': 'added',
  'bulk.preparing': 'Preparing your drafts',
  'bulk.generate': 'Generate drafts',
  'bulk.previewEdit': 'Preview and edit',
  'notifications.title': 'Notifications',
  'notifications.subtitle': 'Your review queue and recent email activity.',
  'notifications.updated': 'Updated',
  'notifications.needsEdit': 'needs edit',
  'notifications.emptyTitle': 'Nothing needs attention',
  'notifications.emptySubtitle':
      'Replies ready for review, urgent emails, and recent sent activity will appear here.',
};

const Map<String, String> _french = {
  'language.title': 'Choisissez votre langue',
  'language.subtitle':
      'Vous pourrez la modifier plus tard dans les paramètres. L’assistant utilisera aussi cette langue pour les brouillons par défaut.',
  'language.english': 'English',
  'language.french': 'Français',
  'language.continue': 'Continuer',
  'nav.home': 'Accueil',
  'nav.today': 'Aujourd’hui',
  'nav.review': 'Revue',
  'nav.profile': 'Profil',
  'auth.signInTitle': 'Connectez-vous à votre boîte intelligente',
  'auth.signInSubtitle':
      'Connectez Outlook pour classer les messages, préparer des brouillons sûrs et garder chaque action sous votre contrôle.',
  'auth.connecting': 'Connexion...',
  'auth.continueOutlook': 'Continuer avec Outlook',
  'auth.errorOutlook':
      'Impossible de se connecter avec Outlook. Veuillez réessayer.',
  'onboarding.skip': 'Passer',
  'onboarding.openAssistant': 'Ouvrir l’assistant',
  'onboarding.getStarted': 'Commencer',
  'onboarding.connected': 'Outlook connecté',
  'onboarding.primary': '12 principaux',
  'onboarding.priority': '5 prioritaires',
  'onboarding.connectTitle': 'Connectez votre boîte mail',
  'onboarding.connectDescription':
      'Laissez TT Mail Assistant classer, prioriser et préparer des réponses avant que les emails ne vous submergent.',
  'onboarding.reviewProtected': 'Revue protégée',
  'onboarding.urgentHeld': 'Urgents retenus',
  'onboarding.draftChecked': 'Brouillon vérifié',
  'onboarding.controlTitle': 'Gardez le contrôle',
  'onboarding.controlDescription':
      'Les réponses urgentes ou incertaines attendent votre validation, tandis que les emails simples avancent discrètement.',
  'onboarding.repliesReady': 'Réponses prêtes',
  'onboarding.drafts': '3 brouillons',
  'onboarding.approve': 'Valider en 1 geste',
  'onboarding.answerTitle': 'Répondez plus vite',
  'onboarding.answerDescription':
      'Validez, modifiez ou ignorez les brouillons IA depuis un espace mobile clair pour le tri quotidien.',
  'settings.title': 'Paramètres',
  'settings.subtitle': 'Gérez votre compte et vos préférences email.',
  'settings.emailHandling': 'Traitement des emails',
  'settings.preferences': 'Préférences',
  'settings.appLanguage': 'Langue de l’application',
  'settings.replyLanguage': 'Langue des réponses',
  'settings.replyLanguageSubtitle': 'Rédiger les brouillons dans cette langue.',
  'settings.prepareReplies': 'Préparer les réponses automatiquement',
  'settings.prepareRepliesOn':
      'Les nouveaux emails non lus deviennent des brouillons à vérifier.',
  'settings.prepareRepliesOff':
      'Les nouveaux emails attendront que cette option soit réactivée.',
  'settings.notifications': 'Notifications',
  'settings.notificationsSubtitle':
      'Recevoir une alerte quand une réponse est prête à vérifier.',
  'settings.dailySummary': 'Résumé quotidien',
  'settings.dailySummarySubtitle':
      'Recevoir un court résumé des emails traités.',
  'settings.darkMode': 'Mode sombre',
  'settings.darkModeSubtitle': 'Utiliser une apparence plus sombre.',
  'settings.outlookConnected': 'Outlook connecté',
  'settings.signOut': 'Déconnexion',
  'settings.signOutTitle': 'Se déconnecter ?',
  'settings.signOutMessage': 'Vous devrez reconnecter votre compte Outlook.',
  'settings.cancel': 'Annuler',
  'settings.signOutAction': 'Se déconnecter',
  'settings.user': 'Utilisateur',
  'common.back': 'Retour',
  'common.close': 'Fermer',
  'home.error': 'Erreur',
  'home.recentActivity': 'Activité récente',
  'home.noRecentActivity': 'Aucune activité récente',
  'home.processedAppear': 'Les emails traités apparaîtront ici.',
  'home.shortcuts': 'Raccourcis',
  'home.tools': 'Outils',
  'home.goodMorning': 'Bonjour',
  'home.goodAfternoon': 'Bon après-midi',
  'home.goodEvening': 'Bonsoir',
  'home.notifications': 'Notifications',
  'home.repliesNeedReview': 'réponses à vérifier',
  'home.inboxUnderControl': 'Boîte mail sous contrôle',
  'home.openReview':
      'Ouvrez la revue pour vérifier les brouillons avant envoi.',
  'home.newUnreadAppear':
      'Les nouveaux emails non lus apparaîtront ici après traitement.',
  'home.processedToday': 'Traités aujourd’hui',
  'home.sent': 'Envoyés',
  'home.needReview': 'À vérifier',
  'home.completion': 'Finalisation',
  'home.noSubject': '(Sans objet)',
  'home.unknownSender': 'Expéditeur inconnu',
  'home.reviewReplies': 'Revoir les réponses',
  'home.reviewRepliesShortcut': 'Verifier les reponses suggerees avant envoi.',
  'home.groupDrafts': 'Brouillons groupés',
  'home.groupDraftsShortcut':
      'Preparer le meme message pour plusieurs destinataires.',
  'home.formations': 'Formations',
  'home.formationsShortcut':
      'Importer le planning et envoyer les emails de formation.',
  'formations.title': 'Formations',
  'formations.subtitle': 'Planning, participants et brouillons Outlook.',
  'formations.activePlan': 'Planning courant pret',
  'formations.activePlanHint':
      'Continuez depuis l etape qui demande attention.',
  'formations.noActivePlan': 'Commencer par un planning',
  'formations.noActivePlanHint':
      'Importez le planning Excel du mois pour demarrer.',
  'formations.workflowTitle': 'Parcours formation',
  'formations.imports': 'imports',
  'formations.toCheck': 'a verifier',
  'formations.importStepTitle': 'Planning des sessions',
  'formations.importStepSubtitle':
      'Importer le fichier Excel des sessions de formation.',
  'formations.contactsStepTitle': 'Candidats',
  'formations.contactsStepSubtitle':
      'Importer les candidats et completer les emails.',
  'formations.calendarStepTitle': 'Calendrier',
  'formations.calendarStepSubtitle':
      'Verifier les sessions par date de formation.',
  'formations.draftsStepTitle': 'Brouillons',
  'formations.draftsStepSubtitle': 'Generer, modifier, valider et envoyer.',
  'formations.historyStepTitle': 'Emails envoyes',
  'formations.historyStepSubtitle': 'Controler les envois Outlook.',
  'formations.settingsStepTitle': 'Automatisation',
  'formations.settingsStepSubtitle': 'Regler la preparation des brouillons.',
  'formations.importPageTitle': 'Importer les formations',
  'formations.importPageSubtitle':
      'Ajoutez le planning des sessions puis la liste des candidats.',
  'formations.calendarPageTitle': 'Calendrier formations',
  'formations.calendarPageSubtitle': 'Parcourir les sessions par jour.',
  'formations.draftsPageTitle': 'Verification des brouillons',
  'formations.draftsPageSubtitle': 'Verifier chaque email avant envoi.',
  'formations.contactsPageTitle': 'Candidats',
  'formations.contactsPageSubtitle':
      'Corriger les emails candidats manquants ou incertains.',
  'formations.historyPageTitle': 'Emails envoyes',
  'formations.historyPageSubtitle': 'Voir ce qui a ete envoye depuis Outlook.',
  'formations.uploadTitle': 'Fichier planning des sessions',
  'formations.uploadSubtitle':
      'Importez jusqu’à 5 fichiers Excel avant de préparer les emails de confirmation et de sensibilisation.',
  'formations.uploadAction': 'Ajouter le planning',
  'formations.uploadNext':
      'L’import du planning sera connecté à l’étape suivante.',
  'formations.refresh': 'Actualiser',
  'formations.pickError':
      'Impossible de lire les fichiers de planning selectionnes.',
  'formations.uploadLimit': 'Seuls les 5 premiers fichiers ont ete retenus.',
  'formations.importDone': 'Planning importe avec succes.',
  'formations.importFeedbackTitle': 'Resultat de l import',
  'formations.importPreviewTitle': 'Apercu avant import',
  'formations.importFeedbackClean':
      'Le planning est pret. Aucun probleme bloquant detecte.',
  'formations.importPreviewClean':
      'Ce planning semble pret a importer. Rien n est encore enregistre.',
  'formations.importFeedbackNeedsReview':
      'Le planning est importe, mais certains points demandent attention.',
  'formations.importPreviewNeedsReview':
      'Verifiez ces points avant d enregistrer le planning.',
  'formations.importNoEmailsDetectedSummary':
      'Les candidats ont ete trouves, mais aucun email n est encore detecte.',
  'formations.importPreviewNotSaved':
      'Ceci est seulement un apercu. Confirmez pour enregistrer le planning et preparer les brouillons si l automatisation est activee.',
  'formations.confirmImport': 'Importer le planning',
  'formations.feedbackFiles': 'Fichiers',
  'formations.feedbackMissingEmails': 'Emails manquants',
  'formations.feedbackEmailsDetected': 'Emails detectes',
  'formations.feedbackNoEmailsDetected':
      '0 email candidat detecte pour le moment. C est normal si le planning candidats n est pas encore complete. Importez plus tard le fichier Excel complete pour preparer et envoyer les emails.',
  'formations.feedbackAutomationRan':
      'L automatisation a prepare {generated} brouillons et ignore {skipped} existants.',
  'formations.feedbackAutomationSkipped':
      'La preparation automatique est desactivee. Vous pouvez la lancer plus tard.',
  'formations.feedbackIssueCount':
      '{warnings} alertes et {errors} erreurs detectees.',
  'formations.feedbackFilesTitle': 'Fichiers importes',
  'formations.feedbackFileSessions': '{count} sessions trouvees',
  'formations.importStatusOk': 'pret',
  'formations.importStatusReview': 'revue',
  'formations.importStatusError': 'erreur',
  'formations.importStatusUnknown': 'inconnu',
  'formations.draftsDone': 'Brouillons prets pour verification.',
  'formations.automationDone':
      'Automatisation terminee. Brouillons prets pour verification.',
  'formations.contactsTitle': 'Liste des candidats',
  'formations.contactsSubtitle':
      'Importez le fichier Excel ou CSV avec matricules, noms, residences, RH et emails si disponibles.',
  'formations.contactsUpload': 'Importer les candidats',
  'formations.contactsImported': 'Liste des candidats importee et appliquee.',
  'formations.contactPickError':
      'Impossible de lire les fichiers candidats selectionnes.',
  'formations.fixContact': 'Corriger le contact',
  'formations.emailAddress': 'Adresse email',
  'formations.invalidEmail': 'Saisissez une adresse email valide.',
  'formations.saveContact': 'Enregistrer le contact',
  'formations.monthPlan': 'Vue du mois',
  'formations.sessions': 'Sessions',
  'formations.participants': 'Participants',
  'formations.drafts': 'Brouillons',
  'formations.missing': 'Données manquantes',
  'formations.calendarTitle': 'Calendrier des formations',
  'formations.calendarSubtitle': '{count} sessions a venir dans ce planning.',
  'formations.noCalendarSessions':
      'Les sessions de formation apparaitront ici apres l import du planning.',
  'formations.noSessionsForDay': 'Aucune session programmee ce jour.',
  'formations.calendarReady': 'pret',
  'formations.calendarMissing': 'contacts',
  'formations.calendarPlanned': 'prevu',
  'formations.unknownModule': 'Session de formation',
  'formations.locationMissing': 'Lieu manquant',
  'formations.participantsShort': 'participants',
  'formations.candidatesPlannedShort': 'candidats prevus',
  'formations.reviewBeforeSend': 'Verifier avant envoi',
  'formations.reviewBeforeSendHint':
      'Les emails de formation restent bloques jusqu a verification, modification et validation.',
  'formations.generateDrafts': 'Generer les brouillons',
  'formations.runAutomation': 'Lancer l automatisation',
  'formations.automationSettings': 'Parametres d automatisation',
  'formations.automationSettingsSubtitle':
      'Choisissez comment preparer les emails apres l import du planning.',
  'formations.autoRunAfterImport': 'Preparer apres import',
  'formations.autoRunAfterImportHint':
      'Les nouveaux plannings peuvent creer automatiquement des brouillons a verifier.',
  'formations.defaultEmailType': 'Type d email par defaut',
  'formations.emailTypeAuto': 'Choix automatique',
  'formations.emailTypeAwareness': 'Email de sensibilisation',
  'formations.emailTypeConfirmation': 'Confirmation de presence',
  'formations.includePopulation': 'Inclure la liste des participants',
  'formations.includePopulationHint':
      'Ajouter le tableau de la population cible dans les messages generes.',
  'formations.maxDraftsPerRun': 'Brouillons maximum par lancement',
  'formations.saveAutomationSettings': 'Enregistrer',
  'formations.importReady': 'pret',
  'formations.waitingImport': 'en attente',
  'formations.waitingReview': 'Revue',
  'formations.approved': 'Valides',
  'formations.blocked': 'Bloques',
  'formations.sent': 'envoyes',
  'formations.draftsToReview': 'Brouillons a verifier',
  'formations.noDrafts':
      'Aucun brouillon. Importez un planning puis generez les emails de formation.',
  'formations.filterAll': 'Tous',
  'formations.filterReview': 'A verifier',
  'formations.filterApproved': 'Valides',
  'formations.filterSent': 'Envoyes',
  'formations.filterBlocked': 'Bloques',
  'formations.filterRejected': 'Refuses',
  'formations.filterByType': 'Type d email',
  'formations.filterAllTypes': 'Tous les types',
  'formations.sendHistory': 'Historique d envoi',
  'formations.noSendHistory':
      'Les envois Outlook et les echecs apparaitront ici.',
  'formations.sentTo': 'A',
  'formations.sentAt': 'Envoye le',
  'formations.contactsToComplete': 'Candidats a completer',
  'formations.contactReviewTitle': 'Verification des candidats',
  'formations.contactReviewSubtitle':
      'Verifiez les emails candidats manquants et les correspondances par nom avant de preparer ou envoyer les brouillons.',
  'formations.contactReviewReady':
      'Les emails candidats semblent associes. Vous pouvez ouvrir un candidat pour le corriger.',
  'formations.contactReviewMatched': 'Associes',
  'formations.contactReviewNameMatch': 'A verifier',
  'formations.contactReviewMissing': 'Manquants',
  'formations.contactReviewEdit': 'Verifier le candidat',
  'formations.contactReviewNoEmail': 'Aucun email',
  'formations.contactMatchMissing': 'manquant',
  'formations.contactMatchMatricule': 'matricule',
  'formations.contactMatchName': 'nom',
  'formations.contactMatchPlanning': 'planning',
  'formations.contactMatchReview': 'revue',
  'formations.noSubject': '(Sans objet)',
  'formations.noRecipients': 'Aucun destinataire',
  'formations.reviewDraft': 'Verifier le brouillon',
  'formations.regenerateDraft': 'Regenerer le brouillon',
  'formations.regenerateAction': 'Regenerer',
  'formations.regenerateWarning':
      'Cette action remplacera l objet, le message et les destinataires par une nouvelle version generee.',
  'formations.regenerateDone': 'Brouillon regenere. Verifiez le avant envoi.',
  'formations.recipients': 'Destinataires',
  'formations.cc': 'Cc',
  'formations.optional': 'Optionnel',
  'formations.subject': 'Objet',
  'formations.message': 'Message',
  'formations.reject': 'Refuser',
  'formations.save': 'Enregistrer',
  'formations.approve': 'Valider',
  'formations.sendWithOutlook': 'Envoyer avec Outlook',
  'formations.sendSafetyTitle': 'Confirmer avant envoi',
  'formations.sendSafetyMessage':
      'Ce message sera envoye depuis Outlook. Verifiez une derniere fois l objet et les destinataires.',
  'formations.sendSafetyRecipients': 'destinataire(s)',
  'formations.sendSafetyCheckbox':
      'J ai verifie les destinataires et le contenu, et je veux envoyer cet email.',
  'formations.statusApproved': 'valide',
  'formations.statusEdited': 'modifie',
  'formations.statusNeedsContacts': 'contacts',
  'formations.statusRejected': 'refuse',
  'formations.statusSent': 'envoye',
  'formations.statusError': 'erreur',
  'formations.statusWaiting': 'revue',
  'formations.workflow': 'Traitement',
  'formations.stepImport': 'Importer sessions et candidats',
  'formations.stepValidate': 'Vérifier les participants et emails',
  'formations.stepDraft': 'Préparer les brouillons Outlook en français',
  'formations.stepSend': 'Revoir, modifier et envoyer',
  'formations.emptyTitle': 'Aucun planning importé',
  'formations.emptySubtitle':
      'Les sessions, participants, brouillons et historiques d’envoi apparaîtront après le premier import.',
  'date.monday': 'Lundi',
  'date.tuesday': 'Mardi',
  'date.wednesday': 'Mercredi',
  'date.thursday': 'Jeudi',
  'date.friday': 'Vendredi',
  'date.saturday': 'Samedi',
  'date.sunday': 'Dimanche',
  'date.jan': 'Jan',
  'date.feb': 'Fév',
  'date.mar': 'Mar',
  'date.apr': 'Avr',
  'date.may': 'Mai',
  'date.jun': 'Juin',
  'date.jul': 'Juil',
  'date.aug': 'Août',
  'date.sep': 'Sep',
  'date.oct': 'Oct',
  'date.nov': 'Nov',
  'date.dec': 'Déc',
  'review.title': 'Revoir les réponses',
  'review.subtitle': 'Vérifiez les réponses suggérées avant leur envoi.',
  'review.urgent': 'urgent',
  'review.ready': 'prêtes',
  'review.readyToSend': 'prêtes à envoyer',
  'filter.all': 'Tous',
  'filter.ready': 'Prêtes',
  'filter.urgent': 'Urgentes',
  'filter.needsEdit': 'À modifier',
  'assistant.title': 'Demander à l’assistant',
  'assistant.working': 'Traitement de votre demande',
  'assistant.ready': 'Prêt pour les tâches email',
  'assistant.unreachable':
      'Impossible de joindre l’assistant. Vérifiez les services backend puis réessayez.',
  'assistant.confirmed': 'Action confirmée avec succès.',
  'assistant.cancelled': 'Action annulée.',
  'assistant.unreadSummary': 'Résumé non lu',
  'assistant.urgentEmails': 'Emails urgents',
  'assistant.classifyInbox': 'Classer la boîte',
  'assistant.reviewQueue': 'File de revue',
  'assistant.promptUnread': 'Lis et résume mon dernier email non lu',
  'assistant.promptUrgent': 'Montre-moi mes emails urgents',
  'assistant.promptClassify': 'Classe ma boîte mail',
  'assistant.promptReview': 'Quels emails sont prêts à être vérifiés ?',
  'assistant.thinking': 'Réflexion',
  'assistant.inputHint': 'Posez une question sur vos emails...',
  'assistant.emptyTitle': 'Que voulez-vous traiter ?',
  'assistant.emptySubtitle':
      'Demandez des résumés, priorités, brouillons ou mises à jour de la revue.',
  'assistant.summarizeLatest': 'Résumer le dernier',
  'assistant.findUrgent': 'Trouver les urgents',
  'assistant.confirmAction': 'Confirmer l’action',
  'assistant.confirm': 'Confirmer',
  'today.title': 'Aujourd’hui',
  'today.subtitle': 'Suivez ce qui s’est passé avec vos emails aujourd’hui.',
  'today.previousDay': 'Jour précédent',
  'today.waitingReview': 'en attente de revue',
  'today.yesterday': 'Hier',
  'today.refreshHint': 'Tirez vers le bas pour actualiser la chronologie.',
  'today.emptyAll': 'Aucune activité pour ce jour',
  'today.emptySent': 'Aucune réponse envoyée',
  'today.emptyReview': 'Rien en attente de revue',
  'today.emptyLow': 'Aucun email de faible priorité',
  'filter.sent': 'Envoyés',
  'filter.review': 'Revue',
  'filter.low': 'Faible',
  'bulk.campaign': 'Campagne',
  'bulk.recipients': 'Destinataires',
  'bulk.added': 'ajoutés',
  'bulk.preparing': 'Préparation de vos brouillons',
  'bulk.generate': 'Générer les brouillons',
  'bulk.previewEdit': 'Prévisualiser et modifier',
  'notifications.title': 'Notifications',
  'notifications.subtitle': 'Votre file de revue et l’activité récente.',
  'notifications.updated': 'Mis à jour',
  'notifications.needsEdit': 'à modifier',
  'notifications.emptyTitle': 'Rien ne demande votre attention',
  'notifications.emptySubtitle':
      'Les réponses prêtes, emails urgents et envois récents apparaîtront ici.',
};
